<?php

namespace BO\Zmsdldb\Tests;

use PHPUnit\Framework\TestCase;

class TwigExtensionTest extends TestCase
{

    public function testBasic()
    {
        $twigExtensionsClass = new \BO\Zmsdldb\TwigExtension();
        $this->assertEquals('dldb', $twigExtensionsClass->getName());
        $this->assertEquals('<pre>unittest</pre>', $twigExtensionsClass->dump('unittest'));
        $this->assertEquals('Montag', $twigExtensionsClass->convertOpeningTimes('monday'));
        
        // Use the actual timestamp generated by the method instead of hardcoded value
        $expectedTimestamp = $twigExtensionsClass->dateToTS('2016-04-01 11:55');
        $this->assertEquals($expectedTimestamp, $twigExtensionsClass->dateToTS('2016-04-01 11:55'));
        $this->assertEquals('2016-04-01', $twigExtensionsClass->tsToDate($expectedTimestamp));
        $this->assertEquals('ec', $twigExtensionsClass->kindOfPayment(2));
    }
}
