version: 2

updates:
  ##################################################
  # NPM / Node Projects
  ##################################################

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "npm"
    directory: "/zmscitizenview"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "npm"
    directory: "/zmscitizenapi"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "npm"
    directory: "/zmsapi"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "npm"
    directory: "/zmsadmin"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "npm"
    directory: "/zmsstatistic"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "npm"
    directory: "/zmsticketprinter"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "npm"
    directory: "/zmscalldisplay"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "npm"
    directory: "/.devcontainer/mail-viewer"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  ##################################################
  # Composer Projects
  ##################################################

  - package-ecosystem: "composer"
    directory: "/mellon"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "composer"
    directory: "/zmsadmin"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "composer"
    directory: "/zmsapi"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "composer"
    directory: "/zmscalldisplay"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "composer"
    directory: "/zmscitizenapi"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "composer"
    directory: "/zmsclient"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "composer"
    directory: "/zmsdb"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "composer"
    directory: "/zmsdldb"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "composer"
    directory: "/zmsentities"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "composer"
    directory: "/zmsmessaging"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "composer"
    directory: "/zmsslim"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "composer"
    directory: "/zmsstatistic"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  - package-ecosystem: "composer"
    directory: "/zmsticketprinter"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"

  ##################################################
  # Maven (planned)
  ##################################################

  - package-ecosystem: "maven"
    directory: "/zmsautomation"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "next"
