"Type: Feature":
  - head-branch: [ '^feat', '-feature-' ]
"Type: Bug":
  - head-branch: [ '^bug', '^fix', '-bug-', '-fix-' ]
"Type: Maintenance":
  - head-branch: [ '^maint', '-maintenance-' ]
"Type: Documentation":
  - head-branch: [ '^docs', '-documentation-' ]
"Type: Dependency":
  - head-branch: [ '^dep', '^renovate', '-dependency-', '-renovate-' ]
"Type: Security":
  - head-branch: [ '^sec', '-security-' ]
"Type: Chore":
  - head-branch: [ '^chore', '-chore-' ]
"Type: Clean":
  - head-branch: [ '^clean', '-cleanup-', '-clean-' ]

"Documentation: docs":
  - changed-files:
    - any-glob-to-any-file: ['docs/**']

"Documentation: README":
  - changed-files:
    - any-glob-to-any-file: ['README.md']

"Documentation: CHANGELOG":
  - changed-files:
    - any-glob-to-any-file: ['CHANGELOG.md']

"Documentation: CONTRIBUTING":
  - changed-files:
    - any-glob-to-any-file: ['CONTRIBUTING.md']

"Documentation: CODE_OF_CONDUCT":
  - changed-files:
    - any-glob-to-any-file: ['CODE_OF_CONDUCT.md']

"Documentation: SECURITY":
  - changed-files:
    - any-glob-to-any-file: ['SECURITY.md']

"Infrastructure: actions":
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**']

"Infrastructure: devcontainer":
  - changed-files:
    - any-glob-to-any-file: ['.devcontainer/**']

"Infrastructure: ddev":
  - changed-files:
    - any-glob-to-any-file: ['.ddev/**']

"Infrastructure: cli":
  - changed-files:
    - any-glob-to-any-file: ['cli', 'cli_base.py', 'cli_test.py']

"Infrastructure: husky":
  - changed-files:
    - any-glob-to-any-file: ['.husky/**']

"Infrastructure: resources":
  - changed-files:
    - any-glob-to-any-file: ['.resources/**']

"Infrastructure: vscode":
  - changed-files:
    - any-glob-to-any-file: ['.vscode/**']

"Module: mellon":
  - changed-files:
    - any-glob-to-any-file: ['mellon/**']

"Module: zmsadmin":
  - changed-files:
    - any-glob-to-any-file: ['zmsadmin/**']

"Module: zmsbackend":
  - changed-files:
    - any-glob-to-any-file: ['zmsbackend/**']

"Module: zmsautomation":
  - changed-files:
    - any-glob-to-any-file: ['zmsautomation/**']

"Module: zmsbase":
  - changed-files:
    - any-glob-to-any-file: ['zmsbase/**']

"Module: zmscalldisplay":
  - changed-files:
    - any-glob-to-any-file: ['zmscalldisplay/**']

"Module: zmscitizenapi":
  - changed-files:
    - any-glob-to-any-file: ['zmscitizenapi/**']

"Module: zmscitizenview":
  - changed-files:
    - any-glob-to-any-file: ['zmscitizenview/**']

"Module: zmsclient":
  - changed-files:
    - any-glob-to-any-file: ['zmsclient/**']

"Module: zmsbackend":
  - changed-files:
    - any-glob-to-any-file: ['zmsbackend/**']

"Module: zmsdldb":
  - changed-files:
    - any-glob-to-any-file: ['zmsdldb/**']

"Module: zmsentities":
  - changed-files:
    - any-glob-to-any-file: ['zmsentities/**']

"Module: zmslayout":
  - changed-files:
    - any-glob-to-any-file: ['zmslayout/**']

"Module: zmsmessaging":
  - changed-files:
    - any-glob-to-any-file: ['zmsmessaging/**']

"Module: zmsslim":
  - changed-files:
    - any-glob-to-any-file: ['zmsslim/**']

"Module: zmsstatistic":
  - changed-files:
    - any-glob-to-any-file: ['zmsstatistic/**']

"Module: zmsticketprinter":
  - changed-files:
    - any-glob-to-any-file: ['zmsticketprinter/**']