DROP TABLE IF EXISTS `config`;
CREATE TABLE IF NOT EXISTS `config` ( 
	`name` VARCHAR(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL , 
	`value` VARCHAR(250) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL , 
	`changeTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
PRIMARY KEY (`name`)) 
ENGINE = InnoDB 
CHARACTER SET utf8 
COLLATE utf8_unicode_ci;
