-- Restore wartenrstatistik for 2026-08-14 after the daily waiting statistic run did not
-- produce data for that day (CalculateDailyWaitingStatisticByCron).
--
-- Strategy (same recover pattern as 91757926126 / 91770274084, scoped to a single day):
--   1) Aggregate the archived processes of 2026-08-14 from buergerarchiv per scope/hour/type
--   2) Pivot them into the hourly wartenrstatistik layout
--   3) Refresh scopes that already have a row for that date, insert the missing ones
--
-- Unlike 91757926126 / 91770274084 this migration does not DELETE the day first:
--   * 91763967241 dropped the `scopedate` key, so wartenrstatistik has no unique key on
--     (standortid, datum) and INSERT ... ON DUPLICATE KEY UPDATE would duplicate rows.
--   * hour_*_estimated_waiting_time_* is written during the day by ExchangeWaitingscope and
--     not by the daily run, so it must survive the restore.
--
-- Approximation of the cron: the archive keeps a single `Timestamp` (arrival), so the hour
-- bucket comes from it instead of Uhrzeit / wsm_aufnahmezeit, and mitTermin decides the type.
-- Uses the column names after 91775568666 / 91775568667; buergerarchiv.way_time is already
-- stored in minutes, so no unit conversion is needed.
--
-- Idempotent: re-running recalculates the same averages from buergerarchiv.

SET @fix_date := '2026-08-14';

-- 0) Safety: temp table cleanup
DROP TEMPORARY TABLE IF EXISTS tmp_ba_raw;
DROP TEMPORARY TABLE IF EXISTS tmp_ba_agg;
DROP TEMPORARY TABLE IF EXISTS tmp_pivot;

-- 1) Pull the archived processes of the fix date
--    - exclude missed (nicht_erschienen), like the previous restores
--    - exclude rows without a usable scope, like determineValidScopeId() does
CREATE TEMPORARY TABLE tmp_ba_raw ENGINE=Aria AS
SELECT
  StandortID AS scope_id,
  Datum      AS datum,
  HOUR(STR_TO_DATE(`Timestamp`, '%H:%i:%s')) AS bucket_hour,
  CASE WHEN mitTermin = 1 THEN 'termin' ELSE 'spontan' END AS type,
  CASE WHEN waiting_time = 0 THEN NULL ELSE ROUND(waiting_time, 2) END AS waited_minutes,
  COALESCE(way_time, 0) AS way_minutes
FROM buergerarchiv
WHERE Datum = @fix_date
  AND StandortID > 0
  AND (nicht_erschienen IS NULL OR nicht_erschienen = 0);

-- 2) Aggregate per scope/date/hour/type
CREATE TEMPORARY TABLE tmp_ba_agg ENGINE=Aria AS
SELECT
  scope_id,
  datum,
  bucket_hour,
  type,
  COUNT(*)                                AS cnt,
  ROUND(AVG(waited_minutes), 2)           AS avg_wait_minutes,
  ROUND(AVG(COALESCE(way_minutes, 0)), 2) AS avg_way_minutes
FROM tmp_ba_raw
GROUP BY scope_id, datum, bucket_hour, type;

-- 3) Pivot to one row per scope/date with all 24h columns (counts + avg wait + avg way)
CREATE TEMPORARY TABLE tmp_pivot ENGINE=Aria AS
SELECT
  scope_id,
  datum,
  /* counts: spontaneous */
  SUM(CASE WHEN type='spontan' AND bucket_hour= 0 THEN cnt ELSE 0 END) AS hour_00_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour= 1 THEN cnt ELSE 0 END) AS hour_01_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour= 2 THEN cnt ELSE 0 END) AS hour_02_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour= 3 THEN cnt ELSE 0 END) AS hour_03_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour= 4 THEN cnt ELSE 0 END) AS hour_04_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour= 5 THEN cnt ELSE 0 END) AS hour_05_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour= 6 THEN cnt ELSE 0 END) AS hour_06_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour= 7 THEN cnt ELSE 0 END) AS hour_07_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour= 8 THEN cnt ELSE 0 END) AS hour_08_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour= 9 THEN cnt ELSE 0 END) AS hour_09_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=10 THEN cnt ELSE 0 END) AS hour_10_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=11 THEN cnt ELSE 0 END) AS hour_11_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=12 THEN cnt ELSE 0 END) AS hour_12_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=13 THEN cnt ELSE 0 END) AS hour_13_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=14 THEN cnt ELSE 0 END) AS hour_14_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=15 THEN cnt ELSE 0 END) AS hour_15_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=16 THEN cnt ELSE 0 END) AS hour_16_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=17 THEN cnt ELSE 0 END) AS hour_17_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=18 THEN cnt ELSE 0 END) AS hour_18_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=19 THEN cnt ELSE 0 END) AS hour_19_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=20 THEN cnt ELSE 0 END) AS hour_20_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=21 THEN cnt ELSE 0 END) AS hour_21_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=22 THEN cnt ELSE 0 END) AS hour_22_waiting_count_spontaneous,
  SUM(CASE WHEN type='spontan' AND bucket_hour=23 THEN cnt ELSE 0 END) AS hour_23_waiting_count_spontaneous,

  /* counts: appointment */
  SUM(CASE WHEN type='termin' AND bucket_hour= 0 THEN cnt ELSE 0 END) AS hour_00_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour= 1 THEN cnt ELSE 0 END) AS hour_01_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour= 2 THEN cnt ELSE 0 END) AS hour_02_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour= 3 THEN cnt ELSE 0 END) AS hour_03_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour= 4 THEN cnt ELSE 0 END) AS hour_04_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour= 5 THEN cnt ELSE 0 END) AS hour_05_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour= 6 THEN cnt ELSE 0 END) AS hour_06_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour= 7 THEN cnt ELSE 0 END) AS hour_07_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour= 8 THEN cnt ELSE 0 END) AS hour_08_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour= 9 THEN cnt ELSE 0 END) AS hour_09_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=10 THEN cnt ELSE 0 END) AS hour_10_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=11 THEN cnt ELSE 0 END) AS hour_11_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=12 THEN cnt ELSE 0 END) AS hour_12_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=13 THEN cnt ELSE 0 END) AS hour_13_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=14 THEN cnt ELSE 0 END) AS hour_14_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=15 THEN cnt ELSE 0 END) AS hour_15_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=16 THEN cnt ELSE 0 END) AS hour_16_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=17 THEN cnt ELSE 0 END) AS hour_17_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=18 THEN cnt ELSE 0 END) AS hour_18_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=19 THEN cnt ELSE 0 END) AS hour_19_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=20 THEN cnt ELSE 0 END) AS hour_20_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=21 THEN cnt ELSE 0 END) AS hour_21_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=22 THEN cnt ELSE 0 END) AS hour_22_waiting_count_appointment,
  SUM(CASE WHEN type='termin' AND bucket_hour=23 THEN cnt ELSE 0 END) AS hour_23_waiting_count_appointment,

  /* avg wait: spontaneous */
  MAX(CASE WHEN type='spontan' AND bucket_hour= 0 THEN avg_wait_minutes END) AS hour_00_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 1 THEN avg_wait_minutes END) AS hour_01_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 2 THEN avg_wait_minutes END) AS hour_02_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 3 THEN avg_wait_minutes END) AS hour_03_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 4 THEN avg_wait_minutes END) AS hour_04_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 5 THEN avg_wait_minutes END) AS hour_05_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 6 THEN avg_wait_minutes END) AS hour_06_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 7 THEN avg_wait_minutes END) AS hour_07_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 8 THEN avg_wait_minutes END) AS hour_08_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 9 THEN avg_wait_minutes END) AS hour_09_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=10 THEN avg_wait_minutes END) AS hour_10_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=11 THEN avg_wait_minutes END) AS hour_11_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=12 THEN avg_wait_minutes END) AS hour_12_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=13 THEN avg_wait_minutes END) AS hour_13_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=14 THEN avg_wait_minutes END) AS hour_14_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=15 THEN avg_wait_minutes END) AS hour_15_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=16 THEN avg_wait_minutes END) AS hour_16_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=17 THEN avg_wait_minutes END) AS hour_17_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=18 THEN avg_wait_minutes END) AS hour_18_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=19 THEN avg_wait_minutes END) AS hour_19_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=20 THEN avg_wait_minutes END) AS hour_20_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=21 THEN avg_wait_minutes END) AS hour_21_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=22 THEN avg_wait_minutes END) AS hour_22_waiting_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=23 THEN avg_wait_minutes END) AS hour_23_waiting_time_spontaneous,

  /* avg wait: appointment */
  MAX(CASE WHEN type='termin' AND bucket_hour= 0 THEN avg_wait_minutes END) AS hour_00_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 1 THEN avg_wait_minutes END) AS hour_01_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 2 THEN avg_wait_minutes END) AS hour_02_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 3 THEN avg_wait_minutes END) AS hour_03_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 4 THEN avg_wait_minutes END) AS hour_04_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 5 THEN avg_wait_minutes END) AS hour_05_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 6 THEN avg_wait_minutes END) AS hour_06_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 7 THEN avg_wait_minutes END) AS hour_07_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 8 THEN avg_wait_minutes END) AS hour_08_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 9 THEN avg_wait_minutes END) AS hour_09_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=10 THEN avg_wait_minutes END) AS hour_10_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=11 THEN avg_wait_minutes END) AS hour_11_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=12 THEN avg_wait_minutes END) AS hour_12_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=13 THEN avg_wait_minutes END) AS hour_13_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=14 THEN avg_wait_minutes END) AS hour_14_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=15 THEN avg_wait_minutes END) AS hour_15_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=16 THEN avg_wait_minutes END) AS hour_16_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=17 THEN avg_wait_minutes END) AS hour_17_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=18 THEN avg_wait_minutes END) AS hour_18_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=19 THEN avg_wait_minutes END) AS hour_19_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=20 THEN avg_wait_minutes END) AS hour_20_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=21 THEN avg_wait_minutes END) AS hour_21_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=22 THEN avg_wait_minutes END) AS hour_22_waiting_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=23 THEN avg_wait_minutes END) AS hour_23_waiting_time_appointment,

  /* avg way: spontaneous */
  MAX(CASE WHEN type='spontan' AND bucket_hour= 0 THEN avg_way_minutes END) AS hour_00_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 1 THEN avg_way_minutes END) AS hour_01_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 2 THEN avg_way_minutes END) AS hour_02_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 3 THEN avg_way_minutes END) AS hour_03_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 4 THEN avg_way_minutes END) AS hour_04_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 5 THEN avg_way_minutes END) AS hour_05_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 6 THEN avg_way_minutes END) AS hour_06_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 7 THEN avg_way_minutes END) AS hour_07_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 8 THEN avg_way_minutes END) AS hour_08_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour= 9 THEN avg_way_minutes END) AS hour_09_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=10 THEN avg_way_minutes END) AS hour_10_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=11 THEN avg_way_minutes END) AS hour_11_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=12 THEN avg_way_minutes END) AS hour_12_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=13 THEN avg_way_minutes END) AS hour_13_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=14 THEN avg_way_minutes END) AS hour_14_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=15 THEN avg_way_minutes END) AS hour_15_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=16 THEN avg_way_minutes END) AS hour_16_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=17 THEN avg_way_minutes END) AS hour_17_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=18 THEN avg_way_minutes END) AS hour_18_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=19 THEN avg_way_minutes END) AS hour_19_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=20 THEN avg_way_minutes END) AS hour_20_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=21 THEN avg_way_minutes END) AS hour_21_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=22 THEN avg_way_minutes END) AS hour_22_way_time_spontaneous,
  MAX(CASE WHEN type='spontan' AND bucket_hour=23 THEN avg_way_minutes END) AS hour_23_way_time_spontaneous,

  /* avg way: appointment */
  MAX(CASE WHEN type='termin' AND bucket_hour= 0 THEN avg_way_minutes END) AS hour_00_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 1 THEN avg_way_minutes END) AS hour_01_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 2 THEN avg_way_minutes END) AS hour_02_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 3 THEN avg_way_minutes END) AS hour_03_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 4 THEN avg_way_minutes END) AS hour_04_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 5 THEN avg_way_minutes END) AS hour_05_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 6 THEN avg_way_minutes END) AS hour_06_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 7 THEN avg_way_minutes END) AS hour_07_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 8 THEN avg_way_minutes END) AS hour_08_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour= 9 THEN avg_way_minutes END) AS hour_09_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=10 THEN avg_way_minutes END) AS hour_10_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=11 THEN avg_way_minutes END) AS hour_11_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=12 THEN avg_way_minutes END) AS hour_12_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=13 THEN avg_way_minutes END) AS hour_13_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=14 THEN avg_way_minutes END) AS hour_14_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=15 THEN avg_way_minutes END) AS hour_15_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=16 THEN avg_way_minutes END) AS hour_16_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=17 THEN avg_way_minutes END) AS hour_17_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=18 THEN avg_way_minutes END) AS hour_18_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=19 THEN avg_way_minutes END) AS hour_19_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=20 THEN avg_way_minutes END) AS hour_20_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=21 THEN avg_way_minutes END) AS hour_21_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=22 THEN avg_way_minutes END) AS hour_22_way_time_appointment,
  MAX(CASE WHEN type='termin' AND bucket_hour=23 THEN avg_way_minutes END) AS hour_23_way_time_appointment

FROM tmp_ba_agg
GROUP BY scope_id, datum;

-- 4) Refresh the scopes that already have a row for the fix date
UPDATE wartenrstatistik w
JOIN tmp_pivot p ON p.scope_id = w.standortid AND p.datum = w.datum
SET
  /* counts: spontaneous */
  w.hour_00_waiting_count_spontaneous = COALESCE(p.hour_00_waiting_count_spontaneous, 0),
  w.hour_01_waiting_count_spontaneous = COALESCE(p.hour_01_waiting_count_spontaneous, 0),
  w.hour_02_waiting_count_spontaneous = COALESCE(p.hour_02_waiting_count_spontaneous, 0),
  w.hour_03_waiting_count_spontaneous = COALESCE(p.hour_03_waiting_count_spontaneous, 0),
  w.hour_04_waiting_count_spontaneous = COALESCE(p.hour_04_waiting_count_spontaneous, 0),
  w.hour_05_waiting_count_spontaneous = COALESCE(p.hour_05_waiting_count_spontaneous, 0),
  w.hour_06_waiting_count_spontaneous = COALESCE(p.hour_06_waiting_count_spontaneous, 0),
  w.hour_07_waiting_count_spontaneous = COALESCE(p.hour_07_waiting_count_spontaneous, 0),
  w.hour_08_waiting_count_spontaneous = COALESCE(p.hour_08_waiting_count_spontaneous, 0),
  w.hour_09_waiting_count_spontaneous = COALESCE(p.hour_09_waiting_count_spontaneous, 0),
  w.hour_10_waiting_count_spontaneous = COALESCE(p.hour_10_waiting_count_spontaneous, 0),
  w.hour_11_waiting_count_spontaneous = COALESCE(p.hour_11_waiting_count_spontaneous, 0),
  w.hour_12_waiting_count_spontaneous = COALESCE(p.hour_12_waiting_count_spontaneous, 0),
  w.hour_13_waiting_count_spontaneous = COALESCE(p.hour_13_waiting_count_spontaneous, 0),
  w.hour_14_waiting_count_spontaneous = COALESCE(p.hour_14_waiting_count_spontaneous, 0),
  w.hour_15_waiting_count_spontaneous = COALESCE(p.hour_15_waiting_count_spontaneous, 0),
  w.hour_16_waiting_count_spontaneous = COALESCE(p.hour_16_waiting_count_spontaneous, 0),
  w.hour_17_waiting_count_spontaneous = COALESCE(p.hour_17_waiting_count_spontaneous, 0),
  w.hour_18_waiting_count_spontaneous = COALESCE(p.hour_18_waiting_count_spontaneous, 0),
  w.hour_19_waiting_count_spontaneous = COALESCE(p.hour_19_waiting_count_spontaneous, 0),
  w.hour_20_waiting_count_spontaneous = COALESCE(p.hour_20_waiting_count_spontaneous, 0),
  w.hour_21_waiting_count_spontaneous = COALESCE(p.hour_21_waiting_count_spontaneous, 0),
  w.hour_22_waiting_count_spontaneous = COALESCE(p.hour_22_waiting_count_spontaneous, 0),
  w.hour_23_waiting_count_spontaneous = COALESCE(p.hour_23_waiting_count_spontaneous, 0),

  /* counts: appointment */
  w.hour_00_waiting_count_appointment = COALESCE(p.hour_00_waiting_count_appointment, 0),
  w.hour_01_waiting_count_appointment = COALESCE(p.hour_01_waiting_count_appointment, 0),
  w.hour_02_waiting_count_appointment = COALESCE(p.hour_02_waiting_count_appointment, 0),
  w.hour_03_waiting_count_appointment = COALESCE(p.hour_03_waiting_count_appointment, 0),
  w.hour_04_waiting_count_appointment = COALESCE(p.hour_04_waiting_count_appointment, 0),
  w.hour_05_waiting_count_appointment = COALESCE(p.hour_05_waiting_count_appointment, 0),
  w.hour_06_waiting_count_appointment = COALESCE(p.hour_06_waiting_count_appointment, 0),
  w.hour_07_waiting_count_appointment = COALESCE(p.hour_07_waiting_count_appointment, 0),
  w.hour_08_waiting_count_appointment = COALESCE(p.hour_08_waiting_count_appointment, 0),
  w.hour_09_waiting_count_appointment = COALESCE(p.hour_09_waiting_count_appointment, 0),
  w.hour_10_waiting_count_appointment = COALESCE(p.hour_10_waiting_count_appointment, 0),
  w.hour_11_waiting_count_appointment = COALESCE(p.hour_11_waiting_count_appointment, 0),
  w.hour_12_waiting_count_appointment = COALESCE(p.hour_12_waiting_count_appointment, 0),
  w.hour_13_waiting_count_appointment = COALESCE(p.hour_13_waiting_count_appointment, 0),
  w.hour_14_waiting_count_appointment = COALESCE(p.hour_14_waiting_count_appointment, 0),
  w.hour_15_waiting_count_appointment = COALESCE(p.hour_15_waiting_count_appointment, 0),
  w.hour_16_waiting_count_appointment = COALESCE(p.hour_16_waiting_count_appointment, 0),
  w.hour_17_waiting_count_appointment = COALESCE(p.hour_17_waiting_count_appointment, 0),
  w.hour_18_waiting_count_appointment = COALESCE(p.hour_18_waiting_count_appointment, 0),
  w.hour_19_waiting_count_appointment = COALESCE(p.hour_19_waiting_count_appointment, 0),
  w.hour_20_waiting_count_appointment = COALESCE(p.hour_20_waiting_count_appointment, 0),
  w.hour_21_waiting_count_appointment = COALESCE(p.hour_21_waiting_count_appointment, 0),
  w.hour_22_waiting_count_appointment = COALESCE(p.hour_22_waiting_count_appointment, 0),
  w.hour_23_waiting_count_appointment = COALESCE(p.hour_23_waiting_count_appointment, 0),

  /* avg wait: spontaneous */
  w.hour_00_waiting_time_spontaneous = COALESCE(p.hour_00_waiting_time_spontaneous, 0),
  w.hour_01_waiting_time_spontaneous = COALESCE(p.hour_01_waiting_time_spontaneous, 0),
  w.hour_02_waiting_time_spontaneous = COALESCE(p.hour_02_waiting_time_spontaneous, 0),
  w.hour_03_waiting_time_spontaneous = COALESCE(p.hour_03_waiting_time_spontaneous, 0),
  w.hour_04_waiting_time_spontaneous = COALESCE(p.hour_04_waiting_time_spontaneous, 0),
  w.hour_05_waiting_time_spontaneous = COALESCE(p.hour_05_waiting_time_spontaneous, 0),
  w.hour_06_waiting_time_spontaneous = COALESCE(p.hour_06_waiting_time_spontaneous, 0),
  w.hour_07_waiting_time_spontaneous = COALESCE(p.hour_07_waiting_time_spontaneous, 0),
  w.hour_08_waiting_time_spontaneous = COALESCE(p.hour_08_waiting_time_spontaneous, 0),
  w.hour_09_waiting_time_spontaneous = COALESCE(p.hour_09_waiting_time_spontaneous, 0),
  w.hour_10_waiting_time_spontaneous = COALESCE(p.hour_10_waiting_time_spontaneous, 0),
  w.hour_11_waiting_time_spontaneous = COALESCE(p.hour_11_waiting_time_spontaneous, 0),
  w.hour_12_waiting_time_spontaneous = COALESCE(p.hour_12_waiting_time_spontaneous, 0),
  w.hour_13_waiting_time_spontaneous = COALESCE(p.hour_13_waiting_time_spontaneous, 0),
  w.hour_14_waiting_time_spontaneous = COALESCE(p.hour_14_waiting_time_spontaneous, 0),
  w.hour_15_waiting_time_spontaneous = COALESCE(p.hour_15_waiting_time_spontaneous, 0),
  w.hour_16_waiting_time_spontaneous = COALESCE(p.hour_16_waiting_time_spontaneous, 0),
  w.hour_17_waiting_time_spontaneous = COALESCE(p.hour_17_waiting_time_spontaneous, 0),
  w.hour_18_waiting_time_spontaneous = COALESCE(p.hour_18_waiting_time_spontaneous, 0),
  w.hour_19_waiting_time_spontaneous = COALESCE(p.hour_19_waiting_time_spontaneous, 0),
  w.hour_20_waiting_time_spontaneous = COALESCE(p.hour_20_waiting_time_spontaneous, 0),
  w.hour_21_waiting_time_spontaneous = COALESCE(p.hour_21_waiting_time_spontaneous, 0),
  w.hour_22_waiting_time_spontaneous = COALESCE(p.hour_22_waiting_time_spontaneous, 0),
  w.hour_23_waiting_time_spontaneous = COALESCE(p.hour_23_waiting_time_spontaneous, 0),

  /* avg wait: appointment */
  w.hour_00_waiting_time_appointment = COALESCE(p.hour_00_waiting_time_appointment, 0),
  w.hour_01_waiting_time_appointment = COALESCE(p.hour_01_waiting_time_appointment, 0),
  w.hour_02_waiting_time_appointment = COALESCE(p.hour_02_waiting_time_appointment, 0),
  w.hour_03_waiting_time_appointment = COALESCE(p.hour_03_waiting_time_appointment, 0),
  w.hour_04_waiting_time_appointment = COALESCE(p.hour_04_waiting_time_appointment, 0),
  w.hour_05_waiting_time_appointment = COALESCE(p.hour_05_waiting_time_appointment, 0),
  w.hour_06_waiting_time_appointment = COALESCE(p.hour_06_waiting_time_appointment, 0),
  w.hour_07_waiting_time_appointment = COALESCE(p.hour_07_waiting_time_appointment, 0),
  w.hour_08_waiting_time_appointment = COALESCE(p.hour_08_waiting_time_appointment, 0),
  w.hour_09_waiting_time_appointment = COALESCE(p.hour_09_waiting_time_appointment, 0),
  w.hour_10_waiting_time_appointment = COALESCE(p.hour_10_waiting_time_appointment, 0),
  w.hour_11_waiting_time_appointment = COALESCE(p.hour_11_waiting_time_appointment, 0),
  w.hour_12_waiting_time_appointment = COALESCE(p.hour_12_waiting_time_appointment, 0),
  w.hour_13_waiting_time_appointment = COALESCE(p.hour_13_waiting_time_appointment, 0),
  w.hour_14_waiting_time_appointment = COALESCE(p.hour_14_waiting_time_appointment, 0),
  w.hour_15_waiting_time_appointment = COALESCE(p.hour_15_waiting_time_appointment, 0),
  w.hour_16_waiting_time_appointment = COALESCE(p.hour_16_waiting_time_appointment, 0),
  w.hour_17_waiting_time_appointment = COALESCE(p.hour_17_waiting_time_appointment, 0),
  w.hour_18_waiting_time_appointment = COALESCE(p.hour_18_waiting_time_appointment, 0),
  w.hour_19_waiting_time_appointment = COALESCE(p.hour_19_waiting_time_appointment, 0),
  w.hour_20_waiting_time_appointment = COALESCE(p.hour_20_waiting_time_appointment, 0),
  w.hour_21_waiting_time_appointment = COALESCE(p.hour_21_waiting_time_appointment, 0),
  w.hour_22_waiting_time_appointment = COALESCE(p.hour_22_waiting_time_appointment, 0),
  w.hour_23_waiting_time_appointment = COALESCE(p.hour_23_waiting_time_appointment, 0),

  /* avg way: spontaneous */
  w.hour_00_way_time_spontaneous = COALESCE(p.hour_00_way_time_spontaneous, 0),
  w.hour_01_way_time_spontaneous = COALESCE(p.hour_01_way_time_spontaneous, 0),
  w.hour_02_way_time_spontaneous = COALESCE(p.hour_02_way_time_spontaneous, 0),
  w.hour_03_way_time_spontaneous = COALESCE(p.hour_03_way_time_spontaneous, 0),
  w.hour_04_way_time_spontaneous = COALESCE(p.hour_04_way_time_spontaneous, 0),
  w.hour_05_way_time_spontaneous = COALESCE(p.hour_05_way_time_spontaneous, 0),
  w.hour_06_way_time_spontaneous = COALESCE(p.hour_06_way_time_spontaneous, 0),
  w.hour_07_way_time_spontaneous = COALESCE(p.hour_07_way_time_spontaneous, 0),
  w.hour_08_way_time_spontaneous = COALESCE(p.hour_08_way_time_spontaneous, 0),
  w.hour_09_way_time_spontaneous = COALESCE(p.hour_09_way_time_spontaneous, 0),
  w.hour_10_way_time_spontaneous = COALESCE(p.hour_10_way_time_spontaneous, 0),
  w.hour_11_way_time_spontaneous = COALESCE(p.hour_11_way_time_spontaneous, 0),
  w.hour_12_way_time_spontaneous = COALESCE(p.hour_12_way_time_spontaneous, 0),
  w.hour_13_way_time_spontaneous = COALESCE(p.hour_13_way_time_spontaneous, 0),
  w.hour_14_way_time_spontaneous = COALESCE(p.hour_14_way_time_spontaneous, 0),
  w.hour_15_way_time_spontaneous = COALESCE(p.hour_15_way_time_spontaneous, 0),
  w.hour_16_way_time_spontaneous = COALESCE(p.hour_16_way_time_spontaneous, 0),
  w.hour_17_way_time_spontaneous = COALESCE(p.hour_17_way_time_spontaneous, 0),
  w.hour_18_way_time_spontaneous = COALESCE(p.hour_18_way_time_spontaneous, 0),
  w.hour_19_way_time_spontaneous = COALESCE(p.hour_19_way_time_spontaneous, 0),
  w.hour_20_way_time_spontaneous = COALESCE(p.hour_20_way_time_spontaneous, 0),
  w.hour_21_way_time_spontaneous = COALESCE(p.hour_21_way_time_spontaneous, 0),
  w.hour_22_way_time_spontaneous = COALESCE(p.hour_22_way_time_spontaneous, 0),
  w.hour_23_way_time_spontaneous = COALESCE(p.hour_23_way_time_spontaneous, 0),

  /* avg way: appointment */
  w.hour_00_way_time_appointment = COALESCE(p.hour_00_way_time_appointment, 0),
  w.hour_01_way_time_appointment = COALESCE(p.hour_01_way_time_appointment, 0),
  w.hour_02_way_time_appointment = COALESCE(p.hour_02_way_time_appointment, 0),
  w.hour_03_way_time_appointment = COALESCE(p.hour_03_way_time_appointment, 0),
  w.hour_04_way_time_appointment = COALESCE(p.hour_04_way_time_appointment, 0),
  w.hour_05_way_time_appointment = COALESCE(p.hour_05_way_time_appointment, 0),
  w.hour_06_way_time_appointment = COALESCE(p.hour_06_way_time_appointment, 0),
  w.hour_07_way_time_appointment = COALESCE(p.hour_07_way_time_appointment, 0),
  w.hour_08_way_time_appointment = COALESCE(p.hour_08_way_time_appointment, 0),
  w.hour_09_way_time_appointment = COALESCE(p.hour_09_way_time_appointment, 0),
  w.hour_10_way_time_appointment = COALESCE(p.hour_10_way_time_appointment, 0),
  w.hour_11_way_time_appointment = COALESCE(p.hour_11_way_time_appointment, 0),
  w.hour_12_way_time_appointment = COALESCE(p.hour_12_way_time_appointment, 0),
  w.hour_13_way_time_appointment = COALESCE(p.hour_13_way_time_appointment, 0),
  w.hour_14_way_time_appointment = COALESCE(p.hour_14_way_time_appointment, 0),
  w.hour_15_way_time_appointment = COALESCE(p.hour_15_way_time_appointment, 0),
  w.hour_16_way_time_appointment = COALESCE(p.hour_16_way_time_appointment, 0),
  w.hour_17_way_time_appointment = COALESCE(p.hour_17_way_time_appointment, 0),
  w.hour_18_way_time_appointment = COALESCE(p.hour_18_way_time_appointment, 0),
  w.hour_19_way_time_appointment = COALESCE(p.hour_19_way_time_appointment, 0),
  w.hour_20_way_time_appointment = COALESCE(p.hour_20_way_time_appointment, 0),
  w.hour_21_way_time_appointment = COALESCE(p.hour_21_way_time_appointment, 0),
  w.hour_22_way_time_appointment = COALESCE(p.hour_22_way_time_appointment, 0),
  w.hour_23_way_time_appointment = COALESCE(p.hour_23_way_time_appointment, 0);

-- 5) Add the scopes that have no row for the fix date yet
--    hour_*_estimated_waiting_time_* keeps its column default for these new rows
INSERT INTO wartenrstatistik (
  standortid,
  datum,
  hour_00_waiting_count_spontaneous,
  hour_01_waiting_count_spontaneous,
  hour_02_waiting_count_spontaneous,
  hour_03_waiting_count_spontaneous,
  hour_04_waiting_count_spontaneous,
  hour_05_waiting_count_spontaneous,
  hour_06_waiting_count_spontaneous,
  hour_07_waiting_count_spontaneous,
  hour_08_waiting_count_spontaneous,
  hour_09_waiting_count_spontaneous,
  hour_10_waiting_count_spontaneous,
  hour_11_waiting_count_spontaneous,
  hour_12_waiting_count_spontaneous,
  hour_13_waiting_count_spontaneous,
  hour_14_waiting_count_spontaneous,
  hour_15_waiting_count_spontaneous,
  hour_16_waiting_count_spontaneous,
  hour_17_waiting_count_spontaneous,
  hour_18_waiting_count_spontaneous,
  hour_19_waiting_count_spontaneous,
  hour_20_waiting_count_spontaneous,
  hour_21_waiting_count_spontaneous,
  hour_22_waiting_count_spontaneous,
  hour_23_waiting_count_spontaneous,
  hour_00_waiting_count_appointment,
  hour_01_waiting_count_appointment,
  hour_02_waiting_count_appointment,
  hour_03_waiting_count_appointment,
  hour_04_waiting_count_appointment,
  hour_05_waiting_count_appointment,
  hour_06_waiting_count_appointment,
  hour_07_waiting_count_appointment,
  hour_08_waiting_count_appointment,
  hour_09_waiting_count_appointment,
  hour_10_waiting_count_appointment,
  hour_11_waiting_count_appointment,
  hour_12_waiting_count_appointment,
  hour_13_waiting_count_appointment,
  hour_14_waiting_count_appointment,
  hour_15_waiting_count_appointment,
  hour_16_waiting_count_appointment,
  hour_17_waiting_count_appointment,
  hour_18_waiting_count_appointment,
  hour_19_waiting_count_appointment,
  hour_20_waiting_count_appointment,
  hour_21_waiting_count_appointment,
  hour_22_waiting_count_appointment,
  hour_23_waiting_count_appointment,
  hour_00_waiting_time_spontaneous,
  hour_01_waiting_time_spontaneous,
  hour_02_waiting_time_spontaneous,
  hour_03_waiting_time_spontaneous,
  hour_04_waiting_time_spontaneous,
  hour_05_waiting_time_spontaneous,
  hour_06_waiting_time_spontaneous,
  hour_07_waiting_time_spontaneous,
  hour_08_waiting_time_spontaneous,
  hour_09_waiting_time_spontaneous,
  hour_10_waiting_time_spontaneous,
  hour_11_waiting_time_spontaneous,
  hour_12_waiting_time_spontaneous,
  hour_13_waiting_time_spontaneous,
  hour_14_waiting_time_spontaneous,
  hour_15_waiting_time_spontaneous,
  hour_16_waiting_time_spontaneous,
  hour_17_waiting_time_spontaneous,
  hour_18_waiting_time_spontaneous,
  hour_19_waiting_time_spontaneous,
  hour_20_waiting_time_spontaneous,
  hour_21_waiting_time_spontaneous,
  hour_22_waiting_time_spontaneous,
  hour_23_waiting_time_spontaneous,
  hour_00_waiting_time_appointment,
  hour_01_waiting_time_appointment,
  hour_02_waiting_time_appointment,
  hour_03_waiting_time_appointment,
  hour_04_waiting_time_appointment,
  hour_05_waiting_time_appointment,
  hour_06_waiting_time_appointment,
  hour_07_waiting_time_appointment,
  hour_08_waiting_time_appointment,
  hour_09_waiting_time_appointment,
  hour_10_waiting_time_appointment,
  hour_11_waiting_time_appointment,
  hour_12_waiting_time_appointment,
  hour_13_waiting_time_appointment,
  hour_14_waiting_time_appointment,
  hour_15_waiting_time_appointment,
  hour_16_waiting_time_appointment,
  hour_17_waiting_time_appointment,
  hour_18_waiting_time_appointment,
  hour_19_waiting_time_appointment,
  hour_20_waiting_time_appointment,
  hour_21_waiting_time_appointment,
  hour_22_waiting_time_appointment,
  hour_23_waiting_time_appointment,
  hour_00_way_time_spontaneous,
  hour_01_way_time_spontaneous,
  hour_02_way_time_spontaneous,
  hour_03_way_time_spontaneous,
  hour_04_way_time_spontaneous,
  hour_05_way_time_spontaneous,
  hour_06_way_time_spontaneous,
  hour_07_way_time_spontaneous,
  hour_08_way_time_spontaneous,
  hour_09_way_time_spontaneous,
  hour_10_way_time_spontaneous,
  hour_11_way_time_spontaneous,
  hour_12_way_time_spontaneous,
  hour_13_way_time_spontaneous,
  hour_14_way_time_spontaneous,
  hour_15_way_time_spontaneous,
  hour_16_way_time_spontaneous,
  hour_17_way_time_spontaneous,
  hour_18_way_time_spontaneous,
  hour_19_way_time_spontaneous,
  hour_20_way_time_spontaneous,
  hour_21_way_time_spontaneous,
  hour_22_way_time_spontaneous,
  hour_23_way_time_spontaneous,
  hour_00_way_time_appointment,
  hour_01_way_time_appointment,
  hour_02_way_time_appointment,
  hour_03_way_time_appointment,
  hour_04_way_time_appointment,
  hour_05_way_time_appointment,
  hour_06_way_time_appointment,
  hour_07_way_time_appointment,
  hour_08_way_time_appointment,
  hour_09_way_time_appointment,
  hour_10_way_time_appointment,
  hour_11_way_time_appointment,
  hour_12_way_time_appointment,
  hour_13_way_time_appointment,
  hour_14_way_time_appointment,
  hour_15_way_time_appointment,
  hour_16_way_time_appointment,
  hour_17_way_time_appointment,
  hour_18_way_time_appointment,
  hour_19_way_time_appointment,
  hour_20_way_time_appointment,
  hour_21_way_time_appointment,
  hour_22_way_time_appointment,
  hour_23_way_time_appointment
)
SELECT
  p.scope_id,
  p.datum,
  COALESCE(p.hour_00_waiting_count_spontaneous, 0),
  COALESCE(p.hour_01_waiting_count_spontaneous, 0),
  COALESCE(p.hour_02_waiting_count_spontaneous, 0),
  COALESCE(p.hour_03_waiting_count_spontaneous, 0),
  COALESCE(p.hour_04_waiting_count_spontaneous, 0),
  COALESCE(p.hour_05_waiting_count_spontaneous, 0),
  COALESCE(p.hour_06_waiting_count_spontaneous, 0),
  COALESCE(p.hour_07_waiting_count_spontaneous, 0),
  COALESCE(p.hour_08_waiting_count_spontaneous, 0),
  COALESCE(p.hour_09_waiting_count_spontaneous, 0),
  COALESCE(p.hour_10_waiting_count_spontaneous, 0),
  COALESCE(p.hour_11_waiting_count_spontaneous, 0),
  COALESCE(p.hour_12_waiting_count_spontaneous, 0),
  COALESCE(p.hour_13_waiting_count_spontaneous, 0),
  COALESCE(p.hour_14_waiting_count_spontaneous, 0),
  COALESCE(p.hour_15_waiting_count_spontaneous, 0),
  COALESCE(p.hour_16_waiting_count_spontaneous, 0),
  COALESCE(p.hour_17_waiting_count_spontaneous, 0),
  COALESCE(p.hour_18_waiting_count_spontaneous, 0),
  COALESCE(p.hour_19_waiting_count_spontaneous, 0),
  COALESCE(p.hour_20_waiting_count_spontaneous, 0),
  COALESCE(p.hour_21_waiting_count_spontaneous, 0),
  COALESCE(p.hour_22_waiting_count_spontaneous, 0),
  COALESCE(p.hour_23_waiting_count_spontaneous, 0),
  COALESCE(p.hour_00_waiting_count_appointment, 0),
  COALESCE(p.hour_01_waiting_count_appointment, 0),
  COALESCE(p.hour_02_waiting_count_appointment, 0),
  COALESCE(p.hour_03_waiting_count_appointment, 0),
  COALESCE(p.hour_04_waiting_count_appointment, 0),
  COALESCE(p.hour_05_waiting_count_appointment, 0),
  COALESCE(p.hour_06_waiting_count_appointment, 0),
  COALESCE(p.hour_07_waiting_count_appointment, 0),
  COALESCE(p.hour_08_waiting_count_appointment, 0),
  COALESCE(p.hour_09_waiting_count_appointment, 0),
  COALESCE(p.hour_10_waiting_count_appointment, 0),
  COALESCE(p.hour_11_waiting_count_appointment, 0),
  COALESCE(p.hour_12_waiting_count_appointment, 0),
  COALESCE(p.hour_13_waiting_count_appointment, 0),
  COALESCE(p.hour_14_waiting_count_appointment, 0),
  COALESCE(p.hour_15_waiting_count_appointment, 0),
  COALESCE(p.hour_16_waiting_count_appointment, 0),
  COALESCE(p.hour_17_waiting_count_appointment, 0),
  COALESCE(p.hour_18_waiting_count_appointment, 0),
  COALESCE(p.hour_19_waiting_count_appointment, 0),
  COALESCE(p.hour_20_waiting_count_appointment, 0),
  COALESCE(p.hour_21_waiting_count_appointment, 0),
  COALESCE(p.hour_22_waiting_count_appointment, 0),
  COALESCE(p.hour_23_waiting_count_appointment, 0),
  COALESCE(p.hour_00_waiting_time_spontaneous, 0),
  COALESCE(p.hour_01_waiting_time_spontaneous, 0),
  COALESCE(p.hour_02_waiting_time_spontaneous, 0),
  COALESCE(p.hour_03_waiting_time_spontaneous, 0),
  COALESCE(p.hour_04_waiting_time_spontaneous, 0),
  COALESCE(p.hour_05_waiting_time_spontaneous, 0),
  COALESCE(p.hour_06_waiting_time_spontaneous, 0),
  COALESCE(p.hour_07_waiting_time_spontaneous, 0),
  COALESCE(p.hour_08_waiting_time_spontaneous, 0),
  COALESCE(p.hour_09_waiting_time_spontaneous, 0),
  COALESCE(p.hour_10_waiting_time_spontaneous, 0),
  COALESCE(p.hour_11_waiting_time_spontaneous, 0),
  COALESCE(p.hour_12_waiting_time_spontaneous, 0),
  COALESCE(p.hour_13_waiting_time_spontaneous, 0),
  COALESCE(p.hour_14_waiting_time_spontaneous, 0),
  COALESCE(p.hour_15_waiting_time_spontaneous, 0),
  COALESCE(p.hour_16_waiting_time_spontaneous, 0),
  COALESCE(p.hour_17_waiting_time_spontaneous, 0),
  COALESCE(p.hour_18_waiting_time_spontaneous, 0),
  COALESCE(p.hour_19_waiting_time_spontaneous, 0),
  COALESCE(p.hour_20_waiting_time_spontaneous, 0),
  COALESCE(p.hour_21_waiting_time_spontaneous, 0),
  COALESCE(p.hour_22_waiting_time_spontaneous, 0),
  COALESCE(p.hour_23_waiting_time_spontaneous, 0),
  COALESCE(p.hour_00_waiting_time_appointment, 0),
  COALESCE(p.hour_01_waiting_time_appointment, 0),
  COALESCE(p.hour_02_waiting_time_appointment, 0),
  COALESCE(p.hour_03_waiting_time_appointment, 0),
  COALESCE(p.hour_04_waiting_time_appointment, 0),
  COALESCE(p.hour_05_waiting_time_appointment, 0),
  COALESCE(p.hour_06_waiting_time_appointment, 0),
  COALESCE(p.hour_07_waiting_time_appointment, 0),
  COALESCE(p.hour_08_waiting_time_appointment, 0),
  COALESCE(p.hour_09_waiting_time_appointment, 0),
  COALESCE(p.hour_10_waiting_time_appointment, 0),
  COALESCE(p.hour_11_waiting_time_appointment, 0),
  COALESCE(p.hour_12_waiting_time_appointment, 0),
  COALESCE(p.hour_13_waiting_time_appointment, 0),
  COALESCE(p.hour_14_waiting_time_appointment, 0),
  COALESCE(p.hour_15_waiting_time_appointment, 0),
  COALESCE(p.hour_16_waiting_time_appointment, 0),
  COALESCE(p.hour_17_waiting_time_appointment, 0),
  COALESCE(p.hour_18_waiting_time_appointment, 0),
  COALESCE(p.hour_19_waiting_time_appointment, 0),
  COALESCE(p.hour_20_waiting_time_appointment, 0),
  COALESCE(p.hour_21_waiting_time_appointment, 0),
  COALESCE(p.hour_22_waiting_time_appointment, 0),
  COALESCE(p.hour_23_waiting_time_appointment, 0),
  COALESCE(p.hour_00_way_time_spontaneous, 0),
  COALESCE(p.hour_01_way_time_spontaneous, 0),
  COALESCE(p.hour_02_way_time_spontaneous, 0),
  COALESCE(p.hour_03_way_time_spontaneous, 0),
  COALESCE(p.hour_04_way_time_spontaneous, 0),
  COALESCE(p.hour_05_way_time_spontaneous, 0),
  COALESCE(p.hour_06_way_time_spontaneous, 0),
  COALESCE(p.hour_07_way_time_spontaneous, 0),
  COALESCE(p.hour_08_way_time_spontaneous, 0),
  COALESCE(p.hour_09_way_time_spontaneous, 0),
  COALESCE(p.hour_10_way_time_spontaneous, 0),
  COALESCE(p.hour_11_way_time_spontaneous, 0),
  COALESCE(p.hour_12_way_time_spontaneous, 0),
  COALESCE(p.hour_13_way_time_spontaneous, 0),
  COALESCE(p.hour_14_way_time_spontaneous, 0),
  COALESCE(p.hour_15_way_time_spontaneous, 0),
  COALESCE(p.hour_16_way_time_spontaneous, 0),
  COALESCE(p.hour_17_way_time_spontaneous, 0),
  COALESCE(p.hour_18_way_time_spontaneous, 0),
  COALESCE(p.hour_19_way_time_spontaneous, 0),
  COALESCE(p.hour_20_way_time_spontaneous, 0),
  COALESCE(p.hour_21_way_time_spontaneous, 0),
  COALESCE(p.hour_22_way_time_spontaneous, 0),
  COALESCE(p.hour_23_way_time_spontaneous, 0),
  COALESCE(p.hour_00_way_time_appointment, 0),
  COALESCE(p.hour_01_way_time_appointment, 0),
  COALESCE(p.hour_02_way_time_appointment, 0),
  COALESCE(p.hour_03_way_time_appointment, 0),
  COALESCE(p.hour_04_way_time_appointment, 0),
  COALESCE(p.hour_05_way_time_appointment, 0),
  COALESCE(p.hour_06_way_time_appointment, 0),
  COALESCE(p.hour_07_way_time_appointment, 0),
  COALESCE(p.hour_08_way_time_appointment, 0),
  COALESCE(p.hour_09_way_time_appointment, 0),
  COALESCE(p.hour_10_way_time_appointment, 0),
  COALESCE(p.hour_11_way_time_appointment, 0),
  COALESCE(p.hour_12_way_time_appointment, 0),
  COALESCE(p.hour_13_way_time_appointment, 0),
  COALESCE(p.hour_14_way_time_appointment, 0),
  COALESCE(p.hour_15_way_time_appointment, 0),
  COALESCE(p.hour_16_way_time_appointment, 0),
  COALESCE(p.hour_17_way_time_appointment, 0),
  COALESCE(p.hour_18_way_time_appointment, 0),
  COALESCE(p.hour_19_way_time_appointment, 0),
  COALESCE(p.hour_20_way_time_appointment, 0),
  COALESCE(p.hour_21_way_time_appointment, 0),
  COALESCE(p.hour_22_way_time_appointment, 0),
  COALESCE(p.hour_23_way_time_appointment, 0)
FROM tmp_pivot p
LEFT JOIN wartenrstatistik w
  ON w.standortid = p.scope_id AND w.datum = p.datum
WHERE w.wartenrstatistikid IS NULL;

-- 6) Cleanup temp tables for long-running sessions
DROP TEMPORARY TABLE IF EXISTS tmp_ba_raw;
DROP TEMPORARY TABLE IF EXISTS tmp_ba_agg;
DROP TEMPORARY TABLE IF EXISTS tmp_pivot;
