ARG PHP_VERSION
FROM registry.gitlab.com/eappointment/php-base:${PHP_VERSION}-dev as build
COPY --chown=1000:1000 . /build
ARG MODULE
WORKDIR /build/${MODULE}
USER 1000:1000
RUN make live

ARG PHP_VERSION
FROM registry.gitlab.com/eappointment/php-base:${PHP_VERSION}-base
ARG MODULE
COPY --from=build --chown=0:0 /build/${MODULE} /var/www/html
