ARG PHP_VERSION
FROM ghcr.io/it-at-m/eappointment/zmsbase:${PHP_VERSION}-dev as build
RUN useradd --shell /bin/bash --create-home build
COPY --chown=build:build . /build
ARG MODULE
WORKDIR /build/${MODULE}
USER build:build
ARG APP_VERSION=version.unknown
ENV COMPOSER_MIRROR_PATH_REPOS=1
ENV ZMS_VERSION=${APP_VERSION}
RUN echo "${APP_VERSION}" > VERSION
RUN make live

ARG PHP_VERSION
FROM ghcr.io/it-at-m/eappointment/zmsbase:${PHP_VERSION}-base
RUN docker-apt-clean-install libfcgi-bin
ARG MODULE
COPY --from=build --chown=0:0 /build/${MODULE} /var/www/html
