#!/bin/bash

set -eo pipefail

export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - 
echo "deb https://deb.nodesource.com/${1} bullseye main" | tee /etc/apt/sources.list.d/nodesource.list 
echo "deb-src https://deb.nodesource.com/${1} bullseye main" | tee -a /etc/apt/sources.list.d/nodesource.list 

docker-apt-clean-install nodejs 


