blank_issues_enabled: false
contact_links:
  - name: 📄 eappointment - Documentation
    url: https://github.com/it-at-m/eappointment/issues/new/choose
    about: Open an issue in eappointment if the topic is related to the web documentation
  - name: 💡 Discussions - Ideas
    url: https://github.com/it-at-m/eappointment/discussions/categories/ideas
    about: Feel free to share ideas for the project that are to vague to create a dedicated issue beforehand
  - name: ⁉ Discussions - Q&A
    url: https://github.com/it-at-m/eappointment/discussions/categories/q-a
    about: Please ask questions here
  - name: 🗨 Discussions - General
    url: https://github.com/it-at-m/eappointment/discussions/categories/general
    about: Discuss more general topics here
