package zms.ataf.ui.pages.citizenview.support;

/**
 * Shared JavaScript fragments for zmscitizenview shadow-DOM interactions.
 */
public final class CitizenViewScripts {

    private CitizenViewScripts() {
    }

    public static final String CITIZEN_DOM =
            "function shown(el){var n=el;while(n&&n.nodeType===1){"
                    + "var st=window.getComputedStyle(n);"
                    + "if(st.display==='none'||st.visibility==='hidden'||st.opacity==='0')return false;"
                    + "if(n.parentElement){n=n.parentElement;continue;}"
                    + "var root=n.getRootNode&&n.getRootNode();n=root&&root.host?root.host:null;}return true;}"
                    + "function textOf(n){var s='';if(!n)return s;if(n.nodeType===3)return n.nodeValue||'';"
                    + "if(n.shadowRoot)s+=' '+textOf(n.shadowRoot);"
                    + "var c=n.childNodes;if(c)for(var i=0;i<c.length;i++)s+=' '+textOf(c[i]);"
                    + "return s.replace(/\\s+/g,' ').trim();}"
                    + "function cssAll(sel){var out=[];function scan(root){if(!root||!root.querySelectorAll)return;"
                    + "var nodes=root.querySelectorAll(sel);for(var i=0;i<nodes.length;i++)out.push(nodes[i]);"
                    + "var all=root.querySelectorAll('*');for(var j=0;j<all.length;j++)if(all[j].shadowRoot)scan(all[j].shadowRoot);}"
                    + "scan(document.body);return out;}"
                    + "function byId(id){var all=cssAll('[id]');for(var i=0;i<all.length;i++)if(all[i].id===id)return all[i];return null;}"
                    + "function findButton(root,word){var found=null;function visit(n){if(!n||found)return;"
                    + "var tag=(n.tagName||'').toUpperCase();"
                    + "if((tag==='MUC-BUTTON'||tag==='BUTTON')&&shown(n)){var t=textOf(n);"
                    + "if(t.indexOf(word)>=0&&t.length<=word.length+2){found=n;return;}}"
                    + "if(n.shadowRoot)visit(n.shadowRoot);var c=n.children;if(c)for(var i=0;i<c.length;i++)visit(c[i]);}"
                    + "visit(root);return found;}"
                    + "function lineCount(root,word){var node=null;function visit(n){if(!n||node)return;"
                    + "if(n.nodeType===3&&(n.nodeValue||'').replace(/\\s+/g,' ').trim()===word){node=n;return;}"
                    + "if(n.shadowRoot)visit(n.shadowRoot);var c=n.childNodes;if(c)for(var i=0;i<c.length;i++)visit(c[i]);}"
                    + "visit(root);if(!node)return 0;var range=document.createRange();range.selectNodeContents(node);"
                    + "return range.getClientRects().length;}"
                    + "function isDisabled(el){if(!el)return false;var inner=el.shadowRoot&&el.shadowRoot.querySelector('button');"
                    + "function flag(n){return !!(n&&(n.disabled||n.hasAttribute('disabled')||n.getAttribute('aria-disabled')==='true'||(n.classList&&n.classList.contains('disabled'))));}"
                    + "return flag(el)||flag(inner);}"
                    + "function btnState(root,word){var found=findButton(root,word);if(!found)return {present:false};"
                    + "return {present:true,disabled:isDisabled(found),lines:lineCount(found,word)};}"
                    + "function isPrimary(el){return !!el&&((el.getAttribute('variant')||'')==='primary'||(el.classList&&el.classList.contains('m-button--primary')));}";


    public static final String CLICK_STORED_TIMESLOT_SCRIPT =
            "var t=window.__zmsCitizenViewSlotTarget;"
                    + "if(!t)return false;"
                    + "function clickSlotNode(node){"
                    + "if(!node)return false;"
                    + "node.scrollIntoView({block:'center'});"
                    + "if(node.shadowRoot){"
                    + "var b=node.shadowRoot.querySelector('button:not([disabled])');"
                    + "if(b){"
                    + "b.scrollIntoView({block:'center'});"
                    + "try{"
                    + "['pointerdown','mousedown','mouseup','pointerup','click'].forEach(function(ev){"
                    + "b.dispatchEvent(new MouseEvent(ev,{bubbles:true,cancelable:true,view:window}));"
                    + "});"
                    + "}catch(e){}"
                    + "b.click();"
                    + "return true;"
                    + "}"
                    + "}"
                    + "try{node.click();return true;}catch(e){return false;}"
                    + "}"
                    + "var ok=clickSlotNode(t);"
                    + "try{window.__zmsCitizenViewSlotTarget=null;}catch(e){}"
                    + "return ok;";

    /**
     * JS fragment: pick target slot + highlight + store in {@code window.__zmsCitizenViewSlotTarget} (no click).
     * <p>
     * Matches the <strong>real booking OfficeID</strong> via {@code provider-{oid}-timeslot-*} id or
     * {@code data-provider-id} (shared booking: slots for peer 10313237 live under display grid 10489).
     */
    public static String buildScrollSlotHighlightScript() {
        return "var oid=String(arguments[0]);"
                + "var prefix='provider-'+oid+'-timeslot-';"
                + "function collectSlots(root,arr,seen){"
                + " if(!root)return;"
                + " if(root.nodeType===1){"
                + "  var id=root.id||'';"
                + "  var dpi=root.getAttribute?root.getAttribute('data-provider-id'):null;"
                + "  var match=id.indexOf(prefix)===0||String(dpi)===oid;"
                + "  if(match){"
                + "   var node=root;"
                + "   if(!(id.indexOf(prefix)===0)&&root.classList&&root.classList.contains('grid-item')){"
                + "    node=root.querySelector('[id^=\"'+prefix+'\"]')||root.querySelector('.timeslot')||root;"
                + "   }"
                + "   if(node&&!seen.has(node)){seen.add(node);arr.push(node);}"
                + "  }"
                + "  if(root.shadowRoot)collectSlots(root.shadowRoot,arr,seen);"
                + " }"
                + " var c=root.children;if(c)for(var i=0;i<c.length;i++)collectSlots(c[i],arr,seen);"
                + "}"
                + "var slots=[];collectSlots(document.body,slots,new Set());"
                + "if(!slots.length)return false;"
                + "function closestGrid(n){"
                + " while(n){if(n.id&&String(n.id).indexOf('timeslot-grid-provider-')===0)return n;n=n.parentElement;}"
                + " return null;}"
                + "var grid=closestGrid(slots[0]);"
                + "if(grid){grid.scrollIntoView({block:'start'});window.scrollBy(0,200);}"
                + "else{slots[0].scrollIntoView({block:'start'});window.scrollBy(0,200);}"
                + "var minTs=Math.floor(Date.now()/1000)+3600;"
                + "function slotTs(node){"
                + " if(!node||!node.id)return null;"
                + " var m=node.id.match(/-timeslot-(\\d+)$/);"
                + " return m?parseInt(m[1],10):null;}"
                + "var skipArg=(arguments.length>1&&arguments[1]!=null)?String(arguments[1]):String(window.__zmsCitizenViewSkippedSlots||'');"
                + "window.__zmsCitizenViewSkippedSlots=skipArg;"
                + "var skip={};"
                + "skipArg.split(',').forEach(function(s){if(s)skip[s]=1;});"
                + "function skipped(ts){return ts!==null&&skip[String(ts)];}"
                + "var target=null;"
                + "for(var j=0;j<slots.length;j++){"
                + " var ts=slotTs(slots[j]);"
                + " if(ts!==null&&ts>=minTs&&!skipped(ts)){target=slots[j];break;}"
                + "}"
                + "if(!target){"
                + " var nowSec=Math.floor(Date.now()/1000);"
                + " var minSafe=nowSec+300;"
                + " var best=null,bestTs=-1;"
                + " for(var k=0;k<slots.length;k++){"
                + "  var ts2=slotTs(slots[k]);"
                + "  if(ts2!==null&&ts2>=minSafe&&!skipped(ts2)&&ts2>bestTs){best=slots[k];bestTs=ts2;}"
                + " }"
                + " target=best;"
                + "}"
                + "if(!target){"
                + " for(var n=0;n<slots.length;n++){"
                + "  if(!skipped(slotTs(slots[n]))){target=slots[n];break;}"
                + " }"
                + "}"
                + "if(!target)return false;"
                + "function highlightSlot(node){"
                + " if(!node)return;"
                + " node.scrollIntoView({block:'center'});"
                + " try{"
                + " node.style.outline='4px solid #ffbf00';"
                + " node.style.outlineOffset='3px';"
                + " node.style.backgroundColor='rgba(255,191,0,0.25)';"
                + " if(node.shadowRoot){"
                + "  var ib=node.shadowRoot.querySelector('button');"
                + "  if(ib){"
                + "   ib.style.outline='4px solid #ffbf00';"
                + "   ib.style.outlineOffset='3px';"
                + "   ib.style.backgroundColor='rgba(255,191,0,0.2)';"
                + "  }"
                + " }"
                + " }catch(e){}"
                + "}"
                + "highlightSlot(target);"
                + "window.__zmsCitizenViewSlotTarget=target;"
                + "window.__zmsCitizenViewSlotId=(target&&target.id)?target.id:'';"
                + "window.__zmsCitizenViewSlotOfficeId=parseInt(oid,10);"
                + "return true;";
    }
}
