services:
  phpmyadmin:
    image: phpmyadmin:5
    container_name: zms-phpmyadmin
    restart: unless-stopped
    ports:
      - "8036:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_HOST=zms-db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=4000M
    depends_on:
      - db
