-- Add the new columns with the "_termin" suffix
ALTER TABLE `wartenrstatistik`
    ADD `wegezeit_ab_00_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_01_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_02_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_03_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_04_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_05_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_06_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_07_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_08_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_09_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_10_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_11_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_12_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_13_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_14_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_15_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_16_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_17_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_18_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_19_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_20_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_21_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_22_termin` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_23_termin` int(5) UNSIGNED NOT NULL DEFAULT 0;
    
-- Add the new columns with the "_spontan" suffix
ALTER TABLE `wartenrstatistik`
    ADD `wegezeit_ab_00_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_01_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_02_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_03_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_04_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_05_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_06_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_07_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_08_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_09_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_10_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_11_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_12_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_13_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_14_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_15_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_16_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_17_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_18_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_19_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_20_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_21_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_22_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0,
    ADD `wegezeit_ab_23_spontan` int(5) UNSIGNED NOT NULL DEFAULT 0;
    

