ALTER TABLE `log`
    ADD COLUMN IF NOT EXISTS `action` VARCHAR(32) DEFAULT NULL AFTER `type`,
    ADD COLUMN IF NOT EXISTS `display_number` VARCHAR(32) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS `queue_number` INT UNSIGNED DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS `appointment_at` DATETIME DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS `slot_count` TINYINT UNSIGNED DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS `client_name` VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS `services` VARCHAR(512) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS `scope_name` VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS `client_email` VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS `client_phone` VARCHAR(64) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS `process_status` VARCHAR(32) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS `db_status` VARCHAR(32) DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_log_type_ts ON log (type, ts);
CREATE INDEX IF NOT EXISTS idx_log_scope_ts ON log (scope_id, ts);
CREATE INDEX IF NOT EXISTS idx_log_client_name ON log (client_name);
CREATE INDEX IF NOT EXISTS idx_log_action ON log (action);
CREATE INDEX IF NOT EXISTS idx_log_appointment_at ON log (appointment_at);
CREATE INDEX IF NOT EXISTS idx_log_services ON log (services(191));
