services:
  mariadb:
    image: mariadb:12.0
    environment:
      MYSQL_ROOT_PASSWORD: zmsapi
      MYSQL_DATABASE: zmsbo
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3308:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pzmsapi"]
      interval: 10s
      timeout: 10s
      retries: 5

  test:
    depends_on:
      mariadb:
        condition: service_healthy
    image: ghcr.io/it-at-m/eappointment-php-base:8.3-dev
    volumes:
      - type: bind
        source: ".."
        target: "/host"
        read_only: true
      - type: volume
        source: zmsapi-workspace
        target: /tmp/workspace
    environment:
      MYSQL_PORT: "tcp://mariadb:3306"
      MYSQL_DATABASE: zmsbo
      MYSQL_ROOT_PASSWORD: zmsapi
      ZMS_CONFIG_SECURE_TOKEN: secure-token
      PHP_MEMORY_LIMIT: "1G"
    working_dir: /tmp/workspace/zmsapi
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    command: >
      bash -c "
        set -e
        echo 'Installing base dependencies (idempotent)...'
        if [ ! -f /tmp/workspace/.deps_installed ]; then \
          apt update && apt install -y python3 python3-click python3-git mariadb-client rsync && \
          touch /tmp/workspace/.deps_installed; \
        else \
          echo 'Base dependencies already installed. Skipping.'; \
        fi
        echo 'Preparing isolated workspace...'
        mkdir -p /tmp/workspace
        rsync -a --delete --exclude='zmsdb/vendor/' --exclude='zmsapi/vendor/' /host/ /tmp/workspace/
        echo 'Waiting for database to be ready...'
        until mysql -h mariadb -u root -pzmsapi -e 'SELECT 1' >/dev/null 2>&1; do
          echo 'Database not ready yet, waiting...'
          sleep 2
        done
        echo 'Database is ready!'
        cd /tmp/workspace
        if [ ! -d /tmp/workspace/zmsapi/vendor ]; then \
          echo 'Setting up module dependencies (symlinks) in isolated workspace...'; \
          python3 cli modules reference-libraries; \
          echo 'Installing composer dependencies (first run)...'; \
          cd /tmp/workspace/zmsapi && composer install --no-progress --prefer-dist --optimize-autoloader && composer dump-autoload -o; \
        else \
          echo 'Vendor already present. Skipping cli+composer.'; \
        fi
        echo 'Setting PHP memory limit...'
        php -d memory_limit=1G -v
        echo 'Setting up test fixtures...'
        cd /tmp/workspace/zmsapi
        rm -rf data
        ln -s /tmp/workspace/zmsdb/tests/Zmsdb/fixtures data
        php -d memory_limit=1G \
            -d auto_prepend_file=/tmp/workspace/zmsapi/vendor/autoload.php \
            /tmp/workspace/zmsdb/bin/importTestData --commit
      
        echo 'Running tests...'
        php -d memory_limit=1G -d auto_prepend_file=/tmp/workspace/zmsapi/vendor/autoload.php vendor/bin/phpunit
      "
volumes:
  zmsapi-workspace:
