package ataf.web.pages;

import ataf.core.assertions.CustomAssertions;
import ataf.core.logging.ScenarioLogManager;
import ataf.web.controls.FrameControls;
import ataf.web.controls.WindowControls;
import ataf.web.model.LocatorType;
import ataf.web.model.Window;
import ataf.web.model.WindowType;
import org.openqa.selenium.By;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Class responsible for generating random names using an external web service. This class extends
 * the {@link BasePage} and includes methods to set and retrieve
 * random names, as well as to format names for email usage.
 *
 * @author Ludwig Haas (ex.haas02)
 */
public class RandomNameGenerator extends BasePage {

    /**
     * Logger instance for logging events and errors related to random name generation.
     */
    /**
     * The first name generated by the random name generator.
     */
    private String name = "";

    /**
     * The surname generated by the random name generator.
     */
    private String surname = "";

    /**
     * Constructs a {@code RandomNameGenerator} with the specified {@link RemoteWebDriver}.
     *
     * @param driver the {@link RemoteWebDriver} used to interact with the web service.
     */
    public RandomNameGenerator(RemoteWebDriver driver) {
        super(driver);
    }

    /**
     * Navigates to a web page that generates random names, extracts the generated name, and splits it
     * into first name and surname. The method handles frame
     * switching, waits for the necessary elements to load, and logs the extracted names.
     */
    public void setRandomName() {
        try {
            final Window REAL_NAME_CREATOR_WINDOW = WindowControls.newWindow(DRIVER, WindowType.UNKNOWN, org.openqa.selenium.WindowType.TAB);
            FrameControls.setCurrentFrame(FrameControls.DEFAULT_CONTENT);
            navigateToPage("https://realnamecreator.alexjonas.de/#");
            waitForPage("Real Name Creator");
            REAL_NAME_CREATOR_WINDOW.updateWindowTitle(DRIVER);
            final String LOADING_INDICATOR_XPATH = "//img[@src='initial_star.svg']";
            waitForElementByXpath(DEFAULT_EXPLICIT_WAIT_TIME, LOADING_INDICATOR_XPATH, true, false);
            waitForElementToDisappearByXpath(DEFAULT_EXPLICIT_WAIT_TIME, LOADING_INDICATOR_XPATH);
            Pattern pattern = Pattern.compile("[\\p{L}-]+(?:\\s[\\p{L}-]+)*");
            WebDriverWait wait = new WebDriverWait(DRIVER, Duration.ofSeconds(DEFAULT_EXPLICIT_WAIT_TIME));
            wait.until(ExpectedConditions.textMatches(By.id("realname"), pattern));
            String randomName = getWebElementText(DEFAULT_EXPLICIT_WAIT_TIME, "realname", LocatorType.ID);
            Matcher matcher = pattern.matcher(randomName);
            if (matcher.find()) {
                String fullName = matcher.group();
                ScenarioLogManager.getLogger().info("Generated name: {}", fullName);
                int indexOfSeparator = fullName.indexOf(" ");
                name = fullName.substring(0, indexOfSeparator);
                ScenarioLogManager.getLogger().info("Extracted name [{}]", name);
                surname = fullName.substring(indexOfSeparator + 1);
                ScenarioLogManager.getLogger().info("Extracted surname [{}]", surname);
            }
            WindowControls.closeWindow(DRIVER, REAL_NAME_CREATOR_WINDOW);
        } catch (Exception e) {
            CustomAssertions.fail("Could not get a random name!", e);
        }
    }

    /**
     * Returns the generated first name.
     *
     * @return the generated first name.
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the generated surname.
     *
     * @return the generated surname.
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Converts a given full name into a format suitable for email addresses by: - Replacing
     * language-specific characters with their ASCII equivalents. -
     * Removing non-ASCII characters. - Replacing spaces with dots.
     *
     * @param fullName the full name to be formatted.
     * @return the email-conform version of the name.
     */
    public static String getEmailConformName(String fullName) {
        fullName = fullName.toLowerCase();

        // Replace language-specific chars
        String[][] specialChars = {
                { "ß", "ss" }, { "ä", "ae" }, { "ö", "oe" }, { "ü", "ue" }, // German
                { "î", "i" }, { "ï", "i" }, { "ô", "o" }, { "û", "u" }, { "ù", "u" }, { "à", "a" }, { "â", "a" }, { "ç", "c" }, { "è", "e" }, { "é", "e" },
                { "ê", "e" }, { "ë", "e" }, // French
                { "ì", "i" }, { "ò", "o" }, // Italian
                { "ñ", "n" }, { "í", "i" }, { "ó", "o" }, { "ú", "u" }, { "á", "a" }, // Spanish
                { "å", "a" }, { "æ", "ae" }, { "ø", "o" } // Scandinavian
        };
        for (String[] mapping : specialChars) {
            fullName = fullName.replaceAll(mapping[0], mapping[1]);
        }

        // Remove non-ASCII chars
        fullName = fullName.replaceAll("[^\\p{ASCII}]", "");

        // Replace whitespace chars
        fullName = fullName.replaceAll("\\s", ".");

        return fullName;
    }

    /**
     * Returns the email-conform version of the generated full name. The full name is created by
     * concatenating the first name and surname.
     *
     * @return the email-conform version of the generated full name.
     */
    public String getEmailConformName() {
        return getEmailConformName(name + " " + surname);
    }
}
