spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "https://*.ddev.site"
              - "http://localhost:*"
            allowedMethods:
              - '*'
            allowedHeaders:
              - '*'
      routes:
        - id: "citizen-api"
          uri: "http://ddev-zms-web:80"
          predicates:
            - Path=/buergeransicht2/api/citizen/**
          filters:
            - RewritePath=/buergeransicht2/api/citizen/(?<segment>.*), /terminvereinbarung/api/citizen/${segment}
            - RemoveResponseHeader=WWW-Authenticate
        - id: "webcomponent"
          uri: "${WEBCOMPONENT_URI}"
          predicates:
            - Path=/buergeransicht2/**
          filters:
            - RewritePath=/buergeransicht2/(?<segment>.*), /${segment}
            - RemoveResponseHeader=WWW-Authenticate 