# Workflow for scanning GitHub workflows with actionlint
name: Actionlint

on:
  # Runs on pull requests
  pull_request:

jobs:
  actionlint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-actionlint@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0
