# Workflow for scanning GitHub workflows with actionlint
name: Actionlint

on:
  # Runs on pull requests
  pull_request:

jobs:
  actionlint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-actionlint@54b32c7d11363cad45838c9a3d8a8560b93f0e8c # v1.5.4
