name: Build Images and Run Tests

on:
  push:
    tags:
      - '**'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: zmsadmin
            php_version: "8.0"
          - module: zmsapi
            php_version: "8.0"
          - module: zmscalldisplay
            php_version: "7.3"
          - module: zmsmessaging
            php_version: "8.0"
          - module: zmsstatistic
            php_version: "8.0"

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Install python3
        run: sudo apt install -y python3 python3-click python3-git

      - name: Referencing local Modules and Libraries
        run: python3 ./cli modules reference-libraries --no-symlink

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Build Image
        run: |
          tag="${{ github.ref_name }}"
          if [ "${{ github.ref_type }}" = "branch" ]; then
            tag="branch-$tag"
          fi
          docker build . \
            --file ".resources/Containerfile" \
            --tag "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag" \
            --build-arg "MODULE=${{ matrix.module }}" \
            --build-arg "PHP_VERSION=${{ matrix.php_version }}"
          docker push "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag"

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: zmsadmin
            php_version: "8.0"
          - module: zmsapi
            php_version: "8.0"
          - module: zmscalldisplay
            php_version: "7.3"
          - module: zmsmessaging
            php_version: "8.0"
          - module: zmsstatistic
            php_version: "8.0"

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Run Unit Tests
        run: |
          tag="latest" # Adjust this as needed
          modules=("zmsadmin" "zmsapi" "zmscalldisplay" "zmsmessaging" "zmsstatistic")
          for module in "${modules[@]}"; do
            echo "Checking for tests in $module"
            if [ -d "$module/tests" ]; then
              echo "Running PHPUnit tests in $module"
              docker run --rm "ghcr.io/${{ github.repository }}/$module:$tag" /bin/bash -c "cd $module && ./vendor/bin/phpunit"
            else
              echo "No tests found in $module"
            fi
