name: Build Images and Run Tests

on:
  push:
    tags:
      - '**'
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: zmsadmin
            php_version: "8.0"
          - module: zmsapi
            php_version: "8.0"
          - module: zmscalldisplay
            php_version: "7.3"
          - module: zmsmessaging
            php_version: "8.0"
          - module: zmsstatistic
            php_version: "8.0"

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Install python3
        run: sudo apt install -y python3 python3-click python3-git

      - name: Referencing local Modules and Libraries
        run: python3 ./cli modules reference-libraries --no-symlink

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Build Image
        run: |
          tag="${{ github.ref_name }}"
          if [ "${{ github.ref_type }}" = "branch" ]; then
            tag="branch-$tag"
          fi
          docker build . \
            --file ".resources/Containerfile" \
            --tag "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag" \
            --build-arg "MODULE=${{ matrix.module }}" \
            --build-arg "PHP_VERSION=${{ matrix.php_version }}"
          docker push "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag"
         

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.1
        env:
          MYSQL_ROOT_PASSWORD: zmsapi
          MYSQL_DATABASE: zmsbo
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
 
    strategy:
      matrix:
        include:
          - module: zmsapi
            php_version: "8.0"
          - module: zmsadmin
            php_version: "8.0"
          - module: zmscalldisplay
            php_version: "7.3"
          - module: zmsmessaging
            php_version: "8.0"
          - module: zmsstatistic
            php_version: "8.0"
          - module: zmsdb
          - module: zmsentities
          - module: zmsslim
          - module: zmsdldb
      max-parallel: 1  # Ensures jobs run sequentially
  
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main
  
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
          coverage: xdebug
          
      - name: Install Composer Dependencies for All Modules
        run: |
          modules=('zmsadmin' 'zmsapi' 'zmscalldisplay' 'zmsmessaging' 'zmsstatistic' 'zmsdb' 'zmsentities')
          for module in "${modules[@]}"; do
            echo "Installing Composer dependencies for $module"
            (cd "$module" && composer install --no-progress --prefer-dist --optimize-autoloader)
          done

      #- name: List MySQL Databases (Schemas)
        #run: |
          #mysql -h 127.0.0.1 -u root -pzmsapi -e "SHOW DATABASES;"

      #- name: Debug Database Connection
        #run: |
          #docker run --rm --network host mysql:5.7 bash -c "mysql -h 127.0.0.1 -u root -pzmsapi -e 'SHOW DATABASES;'"

      #- name: Debug Network Information
        #run: |
          #echo "Inspecting Docker network..."
          #docker network ls
          #docker network inspect bridge
  
      #- name: Debug Database Hostname
        #run: |
          #echo "Debugging database hostname..."
          #CONTAINER_ID=$(docker ps -qf "ancestor=mariadb:10.1")
          #echo "Container ID: $CONTAINER_ID"
          #docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID

      - name: Wait for MariaDB to be ready
        run: |
          echo "Waiting for MariaDB to be fully ready..."
          sleep 10  # Adjust the sleep time as necessary

      #- name: Extract MariaDB IP Address
        #run: |
          #CONTAINER_ID=$(docker ps -qf "ancestor=mariadb:10.1")
          #MARIADB_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)
          #echo "MARIADB_IP=$MARIADB_IP" >> $GITHUB_ENV

      - name: Prepare Fixture Data
        run: |
          echo "Preparing fixture data..."

          echo "***************************"
          ls -l /var/www/html
          echo "***************************"  
          ls -l /home
          echo "***************************"
          ls -l /home/runner
          echo "***************************"
          ls -l /home/runner/work
          echo "***************************"
          ls -l /home/runner/work/eappointment
          echo "***************************"
          ls -l /home/runner/work/eappointment/eappointment
          echo "***************************"
          ls -l /home/runner/work/eappointment/eappointment/zmsapi/vendor/eappointment/
          echo "***************************"
          ls -l /home/runner/work/eappointment/eappointment/zmsapi/vendor/eappointment/zmsdb/         
          echo "***************************"
          ls -l /home/runner/work/eappointment/eappointment/zmsapi/vendor/eappointment/zmsdb/tests/Zmsdb/fixtures
          echo "***************************"
          ls -l /home/runner/work/eappointment/eappointment/data
          echo "***************************"
          ls -l /home/runner/work/eappointment/eappointment/vendor
          echo "***************************"
          
          #rm -rf /home/runner/work/eappointment/eappointment/data
          #ls -l /home/runner/work/eappointment/eappointment/vendor/eappointment/zmsdb/tests/Zmsdb/fixtures
          #ln -s /home/runner/work/eappointment/eappointment/vendor/eappointment/zmsdb/tests/Zmsdb/fixtures /home/runner/work/eappointment/eappointment/data
          # Alternatively, use cp command if symlinks are not suitable    
          #cp -R /home/runner/work/eappointment/eappointment/vendor/eappointment/zmsdb/tests/Zmsdb/fixtures /var/www/html/data
          # cp -R /home/runner/work/eappointment/eappointment/vendor/eappointment/zmsdb/tests/Zmsdb/fixtures /home/runner/work/eappointment/eappointment/data

        
       
      - name: Set up Database for zmsapi
        run: |
          echo "Setting up database for zmsapi module"
          tag="${{ github.ref_name }}"
          if [ "${{ github.ref_type }}" = "branch" ]; then
            tag="branch-$tag"
          fi
          docker run --rm --network host -v /home/runner/work/eappointment/eappointment:/workspace \
            -e MYSQL_HOST=172.18.0.2 \
            -e MYSQL_DATABASE=zmsbo \
            -e MYSQL_USER=root \
            -e MYSQL_ROOT_PASSWORD=password \
            -e MYSQL_PORT=3306 \
            "ghcr.io/it-at-m/eappointment/zmsapi:$tag" \
            ./vendor/bin/importTestData --commit
 
      - name: Run Unit Tests
        run: |
          ls -l zmsadmin
          ls -l zmsapi
          tag="${{ github.ref_name }}"
          if [ "${{ github.ref_type }}" = "branch" ]; then
            tag="branch-$tag"
          fi
          if [ -d "${{ matrix.module }}/tests" ]; then
            echo "Running PHPUnit tests in ${{ matrix.module }}"
            docker run --rm -v ${{ github.workspace }}:/workspace "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag" /bin/bash -c "cd /workspace/${{ matrix.module }} && ./vendor/bin/phpunit"
          else
            echo "No tests found in ${{ matrix.module }}"
          fi

      - name: Cleanup Database after zmsapi tests
        if: matrix.module == 'zmsapi'
        run: |
          # Add commands to clean up the database after zmsapi tests
          # Example: Drop tables or reset database
          echo "Cleaning up database after zmsapi module tests"
