name: 📚 Build API Documentation

on:
  workflow_call:
    outputs:
      result:
        description: "Build result"
        value: ${{ jobs.build.outputs.result }}

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: '8.3'
          extensions: mbstring, json
          tools: composer

      - name: Install PHP dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash .github/scripts/composer-ci.sh install --working-dir=zmsbackend
          bash .github/scripts/composer-ci.sh install --working-dir=zmscitizenapi

      - name: Run PHP post-install scripts
        run: |
          cd zmsbackend && bin/configure && composer run-script post-install-cmd && cd ..
          cd zmscitizenapi && bin/configure && composer run-script post-install-cmd && cd ..

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '24'

      - name: Install Node.js dependencies
        run: |
          (cd zmsbackend && npm install)
          (cd zmscitizenapi && npm install)

      - name: Build projects
        run: |
          (cd zmsbackend && npm run build)
          (cd zmscitizenapi && npm run build)

      - name: Generate Swagger documentation
        run: |
          (cd zmsbackend && npm run doc && npx swagger-cli bundle -o public/doc/swagger.json public/doc/swagger.yaml)
          (cd zmscitizenapi && npm run doc && npx swagger-cli bundle -o public/doc/swagger.json public/doc/swagger.yaml)

      - name: Upload API docs artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: api-docs
          retention-days: 7
          path: |
            zmsbackend/public/doc/
            zmscitizenapi/public/doc/

      - name: Set job result
        id: set-result
        if: always()
        run: echo "result=${{ job.status }}" >> "$GITHUB_OUTPUT"
