name: Build Images and Run Tests

on:
  push:
    tags:
      - '**'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: zmsadmin
            php_version: "8.0"
          - module: zmsapi
            php_version: "8.0"
          - module: zmscalldisplay
            php_version: "7.3"
          - module: zmsmessaging
            php_version: "8.0"
          - module: zmsstatistic
            php_version: "8.0"

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Install python3
        run: sudo apt install -y python3 python3-click python3-git

      - name: Referencing local Modules and Libraries
        run: python3 ./cli modules reference-libraries --no-symlink

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Build Image
        run: |
          tag="${{ github.ref_name }}"
          if [ "${{ github.ref_type }}" = "branch" ]; then
            tag="branch-$tag"
          fi
          docker build . \
            --file ".resources/Containerfile" \
            --tag "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag" \
            --build-arg "MODULE=${{ matrix.module }}" \
            --build-arg "PHP_VERSION=${{ matrix.php_version }}"
          docker push "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag"

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
    strategy:
      matrix:
        include:
          - module: zmsadmin
            php_version: "8.0"
          - module: zmsapi
            php_version: "8.0"
          - module: zmscalldisplay
            php_version: "7.3"
          - module: zmsmessaging
            php_version: "8.0"
          - module: zmsstatistic
            php_version: "8.0"
      max-parallel: 1  # Ensures jobs run sequentially
  
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main
  
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
          coverage: xdebug
  
      - name: Install Composer Dependencies
        run: |
          cd ${{ matrix.module }}
          composer install --no-progress --prefer-dist --optimize-autoloader
  
      - name: Set up Database for zmsapi
        if: matrix.module == 'zmsapi'
        run: |
          echo "Setting up database for zmsapi module"
          tag="${{ github.ref_name }}"
          if [ "${{ github.ref_type }}" = "branch" ]; then
            tag="branch-$tag"
          fi
          echo "------------------------------------------"
          ls -l ./vendor/bin/
          echo "------------------------------------------"
          docker run --rm -v ${{ github.workspace }}:/workspace --network host "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag" /bin/bash -c "cd /workspace/${{ matrix.module }} && ./vendor/bin/importTestData --commit"

      - name: Run Unit Tests
        run: |
          tag="${{ github.ref_name }}"
          if [ "${{ github.ref_type }}" = "branch" ]; then
            tag="branch-$tag"
          fi
          if [ -d "${{ matrix.module }}/tests" ]; then
            echo "Running PHPUnit tests in ${{ matrix.module }}"
            docker run --rm -v ${{ github.workspace }}:/workspace "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag" /bin/bash -c "cd /workspace/${{ matrix.module }} && ./vendor/bin/phpunit"
          else
            echo "No tests found in ${{ matrix.module }}"
          fi

      - name: Cleanup Database after zmsapi tests
        if: matrix.module == 'zmsapi'
        run: |
          # Add commands to clean up the database after zmsapi tests
          # Example: Drop tables or reset database
          echo "Cleaning up database after zmsapi module tests"
