name: Combined Workflow

on: [push]

jobs:
  call-php-code-quality:
    uses: ./.github/workflows/php-code-quality.yaml

  call-php-unit-tests:
    uses: ./.github/workflows/php-unit-tests.yaml

  combine-php-test-coverage:
    needs: [call-php-unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: List available artifacts
        run: |
          echo "Available artifacts in all-coverage:"
          ls -la all-coverage/ || echo "all-coverage directory not found"
          
      - name: Download all coverage reports
        uses: actions/upload-artifact@v4
        with:
          path: all-coverage
          merge-multiple: true

      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -la all-coverage/

  call-php-build-images:
    needs: [call-php-code-quality, call-php-unit-tests]
    if: |
      always() &&
      needs.call-php-unit-tests.outputs.module-test-result == 'success' &&
      needs.call-php-unit-tests.outputs.zmsapi-test-result == 'success' &&
      needs.call-php-unit-tests.outputs.zmsdb-test-result == 'success' &&
      needs.call-php-unit-tests.outputs.zmsclient-test-result == 'success' &&
      needs.call-php-code-quality.result == 'success'
    uses: ./.github/workflows/php-build-images.yaml