name: Combined Workflow

on: [push]

jobs:
  call-php-code-quality:
    uses: ./.github/workflows/php-code-quality.yaml

  call-php-unit-tests:
    uses: ./.github/workflows/php-unit-tests.yaml

  combine-php-test-coverage:
    needs: [call-php-unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Create directories
        run: |
          mkdir -p all-coverage
          mkdir -p combined-coverage

      - name: Download all coverage reports
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: all-coverage
          merge-multiple: true

      - name: Debug downloaded artifacts
        run: |
          echo "Contents of all-coverage directory:"
          find all-coverage -type f
          echo "Number of coverage reports found:"
          find all-coverage -type f | wc -l

      - name: Combine reports
        run: |
          for module in zmsadmin zmscalldisplay zmscitizenapi zmsdldb zmsentities zmsmessaging zmsslim zmsstatistic zmsticketprinter zmsapi zmsdb zmsclient; do
            if [ -d "all-coverage/coverage-$module" ]; then
              echo "Processing $module coverage"
              mkdir -p "combined-coverage/$module"
              if ! cp -r "all-coverage/coverage-$module"/* "combined-coverage/$module/"; then
                echo "Failed to copy files for $module"
                exit 1
              fi
              echo "Successfully copied files for $module"
            else
              echo "No coverage found for $module"
            fi
          done
          echo "Contents of combined-coverage directory:"
          find combined-coverage -type f

      - name: Upload combined coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: combined-coverage/
          retention-days: 7
  call-php-build-images:
    needs: [call-php-code-quality, call-php-unit-tests]
    if: |
      always() &&
      needs.call-code-quality.result == 'success' &&
      needs.call-unit-tests.result == 'success'
    uses: ./.github/workflows/php-build-images.yaml