name: Combined Workflow

on: [push]

jobs:
  call-php-code-quality:
    uses: ./.github/workflows/php-code-quality.yaml

  call-php-unit-tests:
    uses: ./.github/workflows/php-unit-tests.yaml

  combine-php-test-coverage:
    needs: [call-php-unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Create directories
        run: |
          mkdir -p all-coverage
          mkdir -p combined-coverage
          echo "Created directories:"
          ls -la

      - name: List available artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });
            console.log('Available artifacts:');
            console.log(JSON.stringify(artifacts.data, null, 2));

      - name: Download all coverage reports
        uses: actions/download-artifact@v4
        with:
          name: |
            coverage-zmsadmin
            coverage-zmscalldisplay
            coverage-zmscitizenapi
            coverage-zmsdldb
            coverage-zmsentities
            coverage-zmsmessaging
            coverage-zmsslim
            coverage-zmsstatistic
            coverage-zmsticketprinter
            coverage-zmsapi
            coverage-zmsdb
            coverage-zmsclient
          path: all-coverage
          merge-multiple: true

      - name: Debug downloaded artifacts
        run: |
          echo "Current directory:"
          pwd
          echo "All files:"
          find . -type f
          echo "Contents of all-coverage directory:"
          ls -la all-coverage/ || echo "all-coverage not found or empty"
          echo "Detailed file listing:"
          find all-coverage -type f || echo "No files found in all-coverage"

      - name: Combine reports
        run: |
          echo "Starting report combination..."
          for module in zmsadmin zmscalldisplay zmscitizenapi zmsdldb zmsentities zmsmessaging zmsslim zmsstatistic zmsticketprinter zmsapi zmsdb zmsclient; do
            echo "Checking module: $module"
            if [ -d "all-coverage/coverage-$module" ]; then
              echo "Found coverage for $module"
              mkdir -p "combined-coverage/$module"
              if ! cp -rv "all-coverage/coverage-$module"/* "combined-coverage/$module/"; then
                echo "Failed to copy files for $module"
                ls -la "all-coverage/coverage-$module/"
                exit 1
              fi
              echo "Successfully copied files for $module"
            else
              echo "No coverage found for $module"
            fi
          done
          echo "Final combined-coverage contents:"
          find combined-coverage -type f || echo "No files in combined-coverage"

      - name: Upload combined coverage
        if: hashFiles('combined-coverage/**/*') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: combined-coverage/
          retention-days: 7

  call-php-build-images:
    needs: [call-php-code-quality, call-php-unit-tests]
    if: |
      always() &&
      needs.call-php-code-quality.result == 'success' &&
      needs.call-php-unit-tests.result == 'success'
    uses: ./.github/workflows/php-build-images.yaml