name: Combined Workflow

on: [push]

jobs:

  call-php-code-coverage:
    uses: ./.github/workflows/php-code-coverage.yaml

  call-php-code-quality:
    uses: ./.github/workflows/php-code-quality.yaml

  call-php-unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  check-and-proceed:
    needs: [call-php-code-quality, call-php-unit-tests]
    runs-on: ubuntu-latest
    if: |
      always() &&
      needs.call-php-code-quality.result == 'success' &&
      needs.call-php-unit-tests.result == 'success'
    steps:
      - run: echo "All required checks passed"

  call-build-images:
    needs: check-and-proceed
    if: |
      always() &&
      needs.call-php-unit-tests.result == 'success' &&
      needs.call-php-code-quality.result == 'success'
    uses: ./.github/workflows/build-images.yaml