name: Delete Old Workflow Runs

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
    inputs:
      days_to_keep:
        description: 'Number of days to keep workflow runs (default: 30)'
        required: false
        default: '30'
        type: string

permissions:
  actions: write
  contents: read

jobs:
  delete-old-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: actions/delete-workflow-runs@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          # Keep runs from the last 30 days by default, or use input value
          retain_days: ${{ github.event.inputs.days_to_keep || 30 }}
          # Only delete completed runs (successful, failed, cancelled)
          minimum_run_attempts: 1
          # Delete runs from all workflows except this one
          ignore_workflows: 'Delete Old Workflow Runs'
          # Dry run mode - set to false to actually delete runs
          dry_run: false
