name: Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      coverage_artifact:
        description: 'Name of the coverage reports artifact'
        required: true
        type: string
        default: 'coverage-reports'
      api_docs_artifact:
        description: 'Name of the API documentation artifact'
        required: true
        type: string
        default: 'api-docs'
      security_artifact:
        description: 'Name of the security reports artifact'
        required: true
        type: string
        default: 'security-reports'

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create public directory
        run: mkdir -p public/diagrams

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install jsonschema
          pip install jsonschema jinja2

      - name: Create schema converter script
        run: |
          cat > create_pages.py <<'EOL'
          import json
          import os
          from pathlib import Path
          from jinja2 import Template

          def create_pages(diagrams_dir: Path) -> None:
              """Create index page with Mermaid diagrams."""
              # Get main schema diagrams
              main_schemas = []
              for file in sorted(diagrams_dir.glob('*.mmd')):
                  if not file.name.startswith('citizen_'):
                      main_schemas.append({
                          'name': file.stem,
                          'source': file.read_text().strip()
                      })
              
              # Get citizen schema diagrams
              citizen_schemas = []
              for file in sorted(diagrams_dir.glob('citizen_*.mmd')):
                  citizen_schemas.append({
                      'name': file.stem.replace('citizen_', ''),
                      'source': file.read_text().strip()
                  })
              
              # Create index.html
              template = Template("""
          <!DOCTYPE html>
          <html>
            <head>
              <title>API Schema Class Diagrams</title>
              <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
              <script>
                mermaid.initialize({
                  startOnLoad: true,
                  securityLevel: 'loose',
                  logLevel: 'debug'
                });
              </script>
              <style>
                body {
                  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                  line-height: 1.6;
                  padding: 2rem;
                }
                .diagram {
                  margin: 2rem 0;
                  padding: 1rem;
                  border: 1px solid #eaecef;
                  border-radius: 6px;
                }
              </style>
            </head>
            <body>
              <h1>API Schema Class Diagrams</h1>
              
              <h2>Main API Schema</h2>
              <div id="main-schemas">
                {% for schema in main_schemas %}
                <div class="diagram">
                  <h3>{{ schema.name }}</h3>
                  <pre class="mermaid">{{ schema.source }}</pre>
                </div>
                {% endfor %}
              </div>

              <h2>Citizen API Schema</h2>
              <div id="citizen-schemas">
                {% for schema in citizen_schemas %}
                <div class="diagram">
                  <h3>{{ schema.name }}</h3>
                  <pre class="mermaid">{{ schema.source }}</pre>
                </div>
                {% endfor %}
              </div>
            </body>
          </html>
          """)
              
              # Write index page
              diagrams_dir.joinpath('index.html').write_text(
                  template.render(
                      main_schemas=main_schemas,
                      citizen_schemas=citizen_schemas
                  )
              )

          if __name__ == '__main__':
              create_pages(Path('public/diagrams'))
          EOL

          python create_pages.py

      - name: Create debug page
        run: |
          cat > public/diagrams/debug.html <<EOL
          <!DOCTYPE html>
          <html>
            <head>
              <title>Debug: Mermaid Diagrams</title>
              <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
              <script>
                mermaid.initialize({
                  startOnLoad: true,
                  securityLevel: 'loose',
                  logLevel: 'debug',
                  theme: 'default'
                });
              </script>
              <style>
                .diagram {
                  margin: 2rem 0;
                  padding: 1rem;
                  border: 1px solid #eaecef;
                  border-radius: 6px;
                }
                .source {
                  background: #f6f8fa;
                  padding: 1rem;
                  margin: 1rem 0;
                  white-space: pre;
                  font-family: monospace;
                }
              </style>
            </head>
            <body>
              <h1>Debug: Mermaid Diagrams</h1>
              
              <h2>Main API Schema</h2>
          EOL

          # Add main schema diagrams
          for f in public/diagrams/*.mmd; do
            if [[ ! $f =~ citizen_ ]]; then
              echo "<div class='diagram'>" >> public/diagrams/debug.html
              echo "<h3>$(basename "$f" .mmd)</h3>" >> public/diagrams/debug.html
              echo "<div class='source'>Source:<br>$(cat "$f")</div>" >> public/diagrams/debug.html
              echo "<pre class='mermaid'>" >> public/diagrams/debug.html
              cat "$f" >> public/diagrams/debug.html
              echo "</pre>" >> public/diagrams/debug.html
              echo "</div>" >> public/diagrams/debug.html
            fi
          done

          # Add citizen schema diagrams
          cat >> public/diagrams/debug.html <<EOL
              
              <h2>Citizen API Schema</h2>
          EOL

          for f in public/diagrams/citizen_*.mmd; do
            echo "<div class='diagram'>" >> public/diagrams/debug.html
            echo "<h3>$(basename "$f" .mmd | sed 's/citizen_//')</h3>" >> public/diagrams/debug.html
            echo "<div class='source'>Source:<br>$(cat "$f")</div>" >> public/diagrams/debug.html
            echo "<pre class='mermaid'>" >> public/diagrams/debug.html
            cat "$f" >> public/diagrams/debug.html
            echo "</pre>" >> public/diagrams/debug.html
            echo "</div>" >> public/diagrams/debug.html
          done

          # Close HTML
          cat >> public/diagrams/debug.html <<EOL
              <script>
                // Log any Mermaid errors
                window.onerror = function(msg, url, lineNo, columnNo, error) {
                  const diagram = document.querySelector('pre.mermaid:hover');
                  if (diagram) {
                    const debug = document.createElement('div');
                    debug.className = 'error';
                    debug.innerHTML = '<pre>' + msg + '</pre>';
                    diagram.parentNode.appendChild(debug);
                  }
                  return false;
                };
              </script>
            </body>
          </html>
          EOL


      - name: Create diagrams index page
        run: |
          cat > public/diagrams/index.html <<EOL
          <!DOCTYPE html>
          <html>
            <head>
              <title>API Schema Class Diagrams</title>
              <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
              <script>
                mermaid.initialize({
                  startOnLoad: true,
                  securityLevel: 'loose',
                  logLevel: 'debug'
                });
              </script>
              <style>
                body {
                  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                  line-height: 1.6;
                  padding: 2rem;
                }
                .diagram {
                  margin: 2rem 0;
                  padding: 1rem;
                  border: 1px solid #eaecef;
                  border-radius: 6px;
                }
              </style>
            </head>
            <body>
              <h1>API Schema Class Diagrams</h1>
              
              <h2>Main API Schema</h2>
              <div id="main-schemas">
          EOL

          # Add main schema diagrams
          for f in public/diagrams/*.mmd; do
            if [[ ! \$f =~ citizen_ ]]; then
              echo "<div class='diagram'>" >> public/diagrams/index.html
              echo "<h3>\$(basename "\$f" .mmd)</h3>" >> public/diagrams/index.html
              echo "<pre class='mermaid'>" >> public/diagrams/index.html
              cat "\$f" >> public/diagrams/index.html
              echo "</pre>" >> public/diagrams/index.html
              echo "</div>" >> public/diagrams/index.html
            fi
          done

          cat >> public/diagrams/index.html <<EOL
              </div>

              <h2>Citizen API Schema</h2>
              <div id="citizen-schemas">
          EOL

          # Add citizen schema diagrams
          for f in public/diagrams/citizen_*.mmd; do
            echo "<div class='diagram'>" >> public/diagrams/index.html
            echo "<h3>\$(basename "\$f" .mmd | sed 's/citizen_//')</h3>" >> public/diagrams/index.html
            echo "<pre class='mermaid'>" >> public/diagrams/index.html
            cat "\$f" >> public/diagrams/index.html
            echo "</pre>" >> public/diagrams/index.html
            echo "</div>" >> public/diagrams/index.html
          done

          cat >> public/diagrams/index.html <<EOL
              </div>
            </body>
          </html>
          EOL


      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.coverage_artifact }}
          path: public

      - name: Download API docs
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.api_docs_artifact }}
          path: public

      - name: Download security reports
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.security_artifact }}
          path: public

      - name: Debug - List directory structure
        run: |
          echo "=== Directory Structure ==="
          ls -R public/

      - name: Create index page
        run: |
          cat > public/index.html <<'EOL'
          <!DOCTYPE html>
          <html>
            <head>
              <title>eAppointment Documentation</title>
              <style>
                :root {
                  --primary: #0366d6;
                  --bg: #ffffff;
                  --text: #24292e;
                }
                body {
                  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                  line-height: 1.6;
                  color: var(--text);
                  max-width: 1200px;
                  margin: 0 auto;
                  padding: 2rem;
                  background: var(--bg);
                }
                h1, h2 {
                  border-bottom: 1px solid #eaecef;
                  padding-bottom: 0.3em;
                }
                .grid {
                  display: grid;
                  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                  gap: 2rem;
                  margin: 2rem 0;
                }
                .card {
                  background: #f6f8fa;
                  border-radius: 6px;
                  padding: 1.5rem;
                }
                .card h2 {
                  margin-top: 0;
                }
                ul {
                  list-style-type: none;
                  padding: 0;
                }
                li {
                  margin: 0.5rem 0;
                }
                a {
                  color: var(--primary);
                  text-decoration: none;
                }
                a:hover {
                  text-decoration: underline;
                }
              </style>
              <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
              <script>
                mermaid.initialize({ startOnLoad: true });
              </script>
            </head>
            <body>
              <h1>ZMS eAppointment Technical Documentation</h1>
              
              <div class="grid">
                <div class="card">
                  <h2>API Documentation</h2>
                  <ul>
                    <li><a href="https://it-at-m.github.io/eappointment/zmscitizenapi/public/doc/index.html">Zmscitizenapi API Documentation</a></li>
                    <li><a href="https://it-at-m.github.io/eappointment/zmsapi/public/doc/index.html">Zmsapi Documentation</a></li>
                  </ul>
                </div>

                <div class="card">
                  <h2>Schema Diagrams</h2>
                  <ul>
                    <li><a href="diagrams/index.html">API Schema Class Diagrams</a></li>
                  </ul>
                </div>

                <div class="card">
                  <h2>Code Test Coverage Reports</h2>
                  <ul>
                    <li><a href="coverage/coverage-zmsadmin/html/">Zmsadmin Coverage</a></li>
                    <li><a href="coverage/coverage-zmscalldisplay/html/">Zmscalldisplay Coverage</a></li>
                    <li><a href="coverage/coverage-zmscitizenapi/html/">Zmscitizenapi Coverage</a></li>
                    <li><a href="coverage/coverage-zmsdldb/html/">Zmsdldb Coverage</a></li>
                    <li><a href="coverage/coverage-zmsentities/html/">Zmsentities Coverage</a></li>
                    <li><a href="coverage/coverage-zmsmessaging/html/">Zmsmessaging Coverage</a></li>
                    <li><a href="coverage/coverage-zmsslim/html/">Zmsslim Coverage</a></li>
                    <li><a href="coverage/coverage-zmsstatistic/html/">Zmsstatistic Coverage</a></li>
                    <li><a href="coverage/coverage-zmsticketprinter/html/">Zmsticketprinter Coverage</a></li>
                    <li><a href="coverage/coverage-zmsapi/html/">Zmsapi Coverage</a></li>
                    <li><a href="coverage/coverage-zmsdb/html/">Zmsdb Coverage</a></li>
                    <li><a href="coverage/coverage-zmsclient/html/">Zmsclient Coverage</a></li>
                  </ul>
                </div>

                <div class="card">
                  <h2>OWASP Security Reports</h2>
                  <ul>
                    <li><a href="security/security-report-zmsadmin/dependency-check-report.html">Zmsadmin Security Report</a></li>
                    <li><a href="security/security-report-zmscalldisplay/dependency-check-report.html">Zmscalldisplay Security Report</a></li>
                    <li><a href="security/security-report-zmscitizenapi/dependency-check-report.html">Zmscitizenapi Security Report</a></li>
                    <li><a href="security/security-report-zmsdldb/dependency-check-report.html">Zmsdldb Security Report</a></li>
                    <li><a href="security/security-report-zmsentities/dependency-check-report.html">Zmsentities Security Report</a></li>
                    <li><a href="security/security-report-zmsmessaging/dependency-check-report.html">Zmsmessaging Security Report</a></li>
                    <li><a href="security/security-report-zmsslim/dependency-check-report.html">Zmsslim Security Report</a></li>
                    <li><a href="security/security-report-zmsstatistic/dependency-check-report.html">Zmsstatistic Security Report</a></li>
                    <li><a href="security/security-report-zmsticketprinter/dependency-check-report.html">Zmsticketprinter Security Report</a></li>
                    <li><a href="security/security-report-zmsapi/dependency-check-report.html">Zmsapi Security Report</a></li>
                    <li><a href="security/security-report-zmsdb/dependency-check-report.html">Zmsdb Security Report</a></li>
                    <li><a href="security/security-report-zmsclient/dependency-check-report.html">Zmsclient Security Report</a></li>
                    <li><a href="security/zap/zap-scan-report.html">ZAP Scan Reports</a></li>
                  </ul>
                </div>
              </div>
            </body>
          </html>
          EOL

          # Create diagrams index page
          cat > public/diagrams/index.html <<'EOL'
          <!DOCTYPE html>
          <html>
            <head>
              <title>API Schema Class Diagrams</title>
              <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
              <script>
                mermaid.initialize({ startOnLoad: true });
              </script>
              <style>
                body {
                  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                  line-height: 1.6;
                  padding: 2rem;
                }
                .diagram {
                  margin: 2rem 0;
                  padding: 1rem;
                  border: 1px solid #eaecef;
                  border-radius: 6px;
                }
              </style>
            </head>
            <body>
              <h1>API Schema Class Diagrams</h1>
              
              <h2>Main API Schema</h2>
              <div id="main-schemas">
                $(for f in public/diagrams/*.mmd; do
                  if [[ ! $f =~ citizen_ ]]; then
                    echo "<div class='diagram'>"
                    echo "<h3>$(basename "$f" .mmd)</h3>"
                    echo "<pre class='mermaid'>"
                    cat "$f"
                    echo "</pre>"
                    echo "</div>"
                  fi
                done)
              </div>

              <h2>Citizen API Schema</h2>
              <div id="citizen-schemas">
                $(for f in public/diagrams/citizen_*.mmd; do
                  echo "<div class='diagram'>"
                  echo "<h3>$(basename "$f" .mmd | sed 's/citizen_//')</h3>"
                  echo "<pre class='mermaid'>"
                  cat "$f"
                  echo "</pre>"
                  echo "</div>"
                done)
              </div>
            </body>
          </html>
          EOL

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4