name: Code Coverage

on:
  workflow_call:

jobs:
  module-coverage:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/it-at-m/eappointment-php-base:8.0-dev"
    strategy:
      fail-fast: false
      matrix:
        module: [
          'zmsadmin',
          'zmscalldisplay',
          'zmscitizenapi',
          'zmsdldb',
          'zmsentities',
          'zmsmessaging',
          'zmsslim',
          'zmsstatistic',
          'zmsticketprinter'
        ]
    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: |
          cd "${{ matrix.module }}"
          composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Run coverage
        run: |
          cd "${{ matrix.module }}"
          mkdir -p coverage
          php -dzend_extension=xdebug.so -dmemory_limit=-1 vendor/bin/phpunit \
            --coverage-html coverage/html --coverage-clover coverage/clover.xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-temp-${{ matrix.module }}
          path: ${{ matrix.module }}/coverage/
          retention-days: 1

  zmsapi-coverage:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/it-at-m/eappointment-php-base:8.0-dev"
    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: zmsapi
          MYSQL_DATABASE: zmsbo
          MYSQL_CHARACTER_SET: utf8mb4
          MYSQL_COLLATION: utf8mb4_unicode_ci
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
    steps:
      - uses: actions/checkout@main
      - name: Install python3
        run: |
          apt update
          apt install -y python3 python3-click python3-git
      - name: Reference local modules
        run: python3 ./cli modules reference-libraries --no-symlink
      - name: Install dependencies
        run: |
          cd zmsapi
          composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Setup and run coverage
        env:
          MYSQL_PORT: "tcp://mariadb:3306"
          MYSQL_DATABASE: zmsbo
          MYSQL_ROOT_PASSWORD: zmsapi
        run: |
          cd zmsapi
          rm -rf data
          ln -s vendor/eappointment/zmsdb/tests/Zmsdb/fixtures data
          vendor/bin/importTestData --commit
          mkdir -p coverage
          php -dzend_extension=xdebug.so -dmemory_limit=-1 vendor/bin/phpunit \
            --coverage-html coverage/html --coverage-clover coverage/clover.xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-temp-zmsapi
          path: zmsapi/coverage/
          retention-days: 1

  zmsdb-coverage:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/it-at-m/eappointment-php-base:8.0-dev"
    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: zmsdb
          MYSQL_DATABASE: zmsbo
          MYSQL_CHARACTER_SET: utf8mb4
          MYSQL_COLLATION: utf8mb4_unicode_ci
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
    steps:
      - uses: actions/checkout@main
      - name: Install python3
        run: |
          apt update
          apt install -y python3 python3-click python3-git
      - name: Reference local modules
        run: python3 ./cli modules reference-libraries --no-symlink
      - name: Install dependencies
        run: |
          cd zmsdb
          composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Setup and run coverage
        env:
          MYSQL_PORT: "tcp://mariadb:3306"
          MYSQL_DATABASE: zmsbo
          MYSQL_ROOT_PASSWORD: zmsdb
        run: |
          cd zmsdb
          bin/importTestData --commit
          mkdir -p coverage
          php -dzend_extension=xdebug.so -dmemory_limit=-1 vendor/bin/phpunit \
            --coverage-html coverage/html --coverage-clover coverage/clover.xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-temp-zmsdb
          path: zmsdb/coverage/
          retention-days: 1

  zmsclient-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
          coverage: xdebug

      - name: Install Composer Dependencies
        run: |
          cd zmsclient
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run coverage
        run: |
          /bin/bash -c "cd ./zmsclient && docker-compose up -d && docker-compose exec -T test ./vendor/bin/phpunit --coverage-html coverage/html --coverage-clover coverage/clover.xml"

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-temp-zmsclient
          path: zmsclient/coverage/
          retention-days: 1

  combine-coverage:
    needs: [module-coverage, zmsapi-coverage, zmsdb-coverage, zmsclient-coverage]
    runs-on: ubuntu-latest
    steps:
      - name: Download all coverage reports
        uses: actions/download-artifact@v4
        with:
          path: all-coverage
          merge-multiple: true
      - name: Combine reports
        run: |
          mkdir -p combined-coverage
          for module in zmsadmin zmscalldisplay zmscitizenapi zmsdldb zmsentities zmsmessaging zmsslim zmsstatistic zmsticketprinter zmsapi zmsdb zmsclient; do
            if [ -d "all-coverage/coverage-temp-$module" ]; then
              mkdir -p "combined-coverage/$module"
              cp -r "all-coverage/coverage-temp-$module"/* "combined-coverage/$module/"
            fi
          done
      - name: Upload combined coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: combined-coverage/
          retention-days: 7