name: 🧪 zmsclient unit tests

on:
  workflow_call:
    outputs:
      zmsclient-test-result:
        description: "ZMSClient test result"
        value: ${{ jobs.zmsclient-test.outputs.result }}

permissions:
  contents: read
  actions: write

jobs:
  zmsclient-test:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
          coverage: xdebug

      - name: Install Composer Dependencies
        uses: ./.github/actions/composer-install
        with:
          working-directory: zmsclient
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Unit Tests
        env:
          XDEBUG_MODE: coverage
        run: |
          set -e  # Exit immediately on any error
          cd ./zmsclient
          mkdir -p coverage
          docker compose up -d
          
          echo "Running tests WITH coverage for zmsclient"
          docker compose exec -T test php -dmemory_limit=-1 \
            ./vendor/bin/phpunit \
            --coverage-html coverage/html \
            --coverage-clover coverage/clover.xml \
            --log-junit coverage/junit.xml \
            --display-deprecations --display-warnings --fail-on-deprecation
      - name: Upload Coverage
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-zmsclient
          path: zmsclient/coverage/
          retention-days: 1

      - name: Set job result
        id: set-result
        if: always()
        run: echo "result=${{ job.status }}" >> "$GITHUB_OUTPUT"
