name: build images

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker images
        uses: actions/cache@v4
        with:
          path: /tmp/.docker
          key: ${{ runner.os }}-docker-php83-dev-${{ hashFiles('**/Dockerfile*') }}-${{ hashFiles('**/Containerfile*') }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-docker-php83-dev-
            ${{ runner.os }}-docker-
      - name: Install Composer Dependencies
        run: |
          echo "Installing Composer dependencies for ${{ matrix.module }}"
          (cd "${{ matrix.module }}" && composer install --no-progress --prefer-dist --optimize-autoloader)
        shell: bash
      - name: Download CHANGELOG.md for zmsadmin and zmsstatistic
        if: matrix.module == 'zmsadmin' || matrix.module == 'zmsstatistic'
        run: |
          if [ "${{ matrix.module }}" = "zmsadmin" ]; then
            DIR=zmsadmin
          else
            DIR=zmsstatistic
          fi
          curl -sSL -o $DIR/changelog_build.md https://raw.githubusercontent.com/it-at-m/eappointment/main/CHANGELOG.md
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 20
      - name: Build Image
        run: |
          tag="${{ github.ref_name }}"
          if [ "${{ github.ref_type }}" = "branch" ]; then
            # Sanitize the tag by replacing invalid characters with a hyphen
            tag="branch-$(echo "$tag" | sed 's/[\/:]/-/g')"
          fi
          docker build . \
            --file ".resources/Containerfile" \
            --tag "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag" \
            --build-arg "MODULE=${{ matrix.module }}" \
            --build-arg "PHP_VERSION=${{ matrix.php_version }}"
          docker push "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag"
    strategy:
      matrix:
        include:
          - module: zmsadmin
            php_version: "8.3"
          - module: zmsapi
            php_version: "8.3"
          - module: zmscalldisplay
            php_version: "8.3"
          - module: zmscitizenapi
            php_version: "8.3"
          - module: zmsmessaging
            php_version: "8.3"
          - module: zmsstatistic
            php_version: "8.3"
          - module: zmsticketprinter
            php_version: "8.3"
