name: build images

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main
      - name: Install python3
        run: sudo apt install -y python3 python3-click python3-git


      - name: Install Composer Dependencies
        run: |
          echo "Installing Composer dependencies for ${{ matrix.module }}"
          echo "=== Fetching eappointment dependencies ==="
          (cd "${{ matrix.module }}" && composer show --installed | grep "eappointment/" || echo "No eappointment packages found")
          echo "=== Installing with composer ==="
          (cd "${{ matrix.module }}" && composer install --no-progress --prefer-dist --optimize-autoloader)
          echo "=== Final eappointment dependencies ==="
          (cd "${{ matrix.module }}" && composer show --installed | grep "eappointment/" || echo "No eappointment packages found")
          echo "=== eappointment package sources ==="
          (cd "${{ matrix.module }}" && composer show --installed | grep "eappointment/" | while read line; do
            package=$(echo "$line" | awk '{print $1}')
            echo "Checking source for $package:"
            (cd "${{ matrix.module }}" && composer show "$package" | grep -E "(source|dist)" || echo "  No source info found")
          done)
        shell: bash


      - name: Download CHANGELOG.md for zmsadmin and zmsstatistic
        if: matrix.module == 'zmsadmin' || matrix.module == 'zmsstatistic'
        run: |
          if [ "${{ matrix.module }}" = "zmsadmin" ]; then
            DIR=zmsadmin
          else
            DIR=zmsstatistic
          fi
          curl -sSL -o $DIR/changelog_build.md https://raw.githubusercontent.com/it-at-m/eappointment/main/CHANGELOG.md
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 20
      - name: Build Image
        run: |
          tag="${{ github.ref_name }}"
          if [ "${{ github.ref_type }}" = "branch" ]; then
            # Sanitize the tag by replacing invalid characters with a hyphen
            tag="branch-$(echo "$tag" | sed 's/[\/:]/-/g')"
          fi
          docker build . \
            --file ".resources/Containerfile" \
            --tag "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag" \
            --build-arg "MODULE=${{ matrix.module }}" \
            --build-arg "PHP_VERSION=${{ matrix.php_version }}"
          docker push "ghcr.io/${{ github.repository }}/${{ matrix.module }}:$tag"
    strategy:
      matrix:
        include:
          - module: zmsadmin
            php_version: "8.3"
          - module: zmsapi
            php_version: "8.3"
          - module: zmscalldisplay
            php_version: "8.3"
          - module: zmscitizenapi
            php_version: "8.3"
          - module: zmsmessaging
            php_version: "8.3"
          - module: zmsstatistic
            php_version: "8.3"
          - module: zmsticketprinter
            php_version: "8.3"
