name: 🔍 code quality

on:
  workflow_call:

permissions:
  contents: read

jobs:
  module-code-quality:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/it-at-m/eappointment/zmsbase:${{ matrix.php_version }}-dev@sha256:39fa5ce4b22791e56d4c7d723190301748f2df7839dc1d79470a2c44008ff1fa"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install Composer Dependencies
        uses: ./.github/actions/composer-install
        with:
          working-directory: ${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: PHPCS / PSR-12
        run: |
          cd "${{ matrix.module }}"
          echo "Running phpcs (ignoring warnings)..."
          vendor/bin/phpcs --standard=psr12 --warning-severity=0 src/

      - name: PHPMD
        run: |
          cd "${{ matrix.module }}"
          echo "Running phpmd..."
          vendor/bin/phpmd src/ text ../phpmd.rules.xml

    strategy:
      fail-fast: false
      matrix:
        include:
          - module: mellon
            php_version: "8.4"
          - module: zmsadmin
            php_version: "8.4"
          - module: zmsbackend
            php_version: "8.4"
          - module: zmscalldisplay
            php_version: "8.4"
          - module: zmscitizenapi
            php_version: "8.4"
          - module: zmsclient
            php_version: "8.4"
          - module: zmsdldb
            php_version: "8.4"
          - module: zmsentities
            php_version: "8.4"
          - module: zmsmessaging
            php_version: "8.4"
          - module: zmsslim
            php_version: "8.4"
          - module: zmsstatistic
            php_version: "8.4"
          - module: zmsticketprinter
            php_version: "8.4"