name: 🏷️ Label PRs

on:
  - pull_request_target

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write # permission to create labels if not exist
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-pr-labeler@4ed8f906bab8111fbd9a7af8e3f4129f9b721757 # v1.2.3

