name: 🏷️ Label PRs

on:
  - pull_request_target

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write # permission to create labels if not exist
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-pr-labeler@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0

