name: 🏷️ Label PRs

on:
  - pull_request_target

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write # permission to create labels if not exist
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-pr-labeler@7cb754b2056cebda6c36db344434f85be398c493 # v1.0.25

