# Workflow for deploying static content to Pages
name: Deploy API Documentation to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, json
          tools: composer

      - name: Install PHP dependencies
        run: |
          composer install --working-dir=zmsapi
          composer install --working-dir=zmscitizenapi

      - name: Run PHP post-install scripts
        run: |
          cd zmsapi && bin/configure && composer run-script post-install-cmd && cd ..
          cd zmscitizenapi && bin/configure && composer run-script post-install-cmd && cd ..

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node.js dependencies
        run: |
          cd zmsapi && npm install && cd ..
          cd zmscitizenapi && npm install && cd ..

      - name: Build projects
        run: |
          cd zmsapi && npm run build && cd ..
          cd zmscitizenapi && npm run build && cd ..

      - name: Create site structure
        run: |
          mkdir -p ./_site/zmsapi/public/doc
          mkdir -p ./_site/zmscitizenapi/public/doc

      - name: Generate Swagger documentation
        run: |
          # Generate and copy zmsapi documentation
          cd zmsapi
          # First copy all doc files
          cp -r public/doc/* ../_site/zmsapi/public/doc/
          # Then generate swagger.json
          PUBLIC_DOC_DIR="../_site/zmsapi/public/doc" npm run doc || exit 1
          npx swagger-cli bundle -o ../_site/zmsapi/public/doc/swagger.json public/doc/swagger.yaml || exit 1
          cd ..
          
          # Generate and copy zmscitizenapi documentation
          cd zmscitizenapi
          # First copy all doc files
          cp -r public/doc/* ../_site/zmscitizenapi/public/doc/
          # Then generate swagger.json
          PUBLIC_DOC_DIR="../_site/zmscitizenapi/public/doc" npm run doc || exit 1
          npx swagger-cli bundle -o ../_site/zmscitizenapi/public/doc/swagger.json public/doc/swagger.yaml || exit 1
          cd ..

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
