name: 🛡️ Trivy Security Check

on:
  pull_request:
  workflow_call:
  push:
    branches:
      - main
      - next
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    name: 🛡️ Trivy Security Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Run Trivy Security check on Repository
        uses: it-at-m/lhm_actions/action-templates/actions/action-trivy@1a673d9c3be4a4f59cf29f425bc2b00fc42751fd # v1.0.32