name: 🛡️ Trivy Security Check

on:
  pull_request:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
      - next

jobs:
  build:
    name: 🛡️ Trivy Security Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Run Trivy Security check on Repository
        uses: it-at-m/lhm_actions/action-templates/actions/action-trivy@e9a8422d740d4e9eaef25cfeeb3a5790da97a7aa # v1.2.4
