name: ☕ zmsautomation-maven-build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TZ: Europe/Berlin
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@1a673d9c3be4a4f59cf29f425bc2b00fc42751fd # v1.0.32
      - uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@1a673d9c3be4a4f59cf29f425bc2b00fc42751fd # v1.0.32
        with:
          app-path: zmsautomation
          java-version: "21"

