name: ☕ zmsautomation-maven-build

on:
  pull_request:
  push:
    branches: [main, next]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/next' && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TZ: Europe/Berlin
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0
      - uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0
        with:
          app-path: zmsautomation
          java-version: "21"
