name: ☕ zmsautomation-maven-build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TZ: Europe/Berlin
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@699d5d46ed8bcce2227e2d58101d1dde7a713d53 # v1.2.0
      - uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@699d5d46ed8bcce2227e2d58101d1dde7a713d53 # v1.2.0
        with:
          app-path: zmsautomation
          java-version: "21"

